# ABOUTME: Maps curve identifiers to rateslib-specific market conventions and parameters
# ABOUTME: Defines calendars, day counters, business conventions for each swap curve type
from typing import Dict
import rateslib as rl

from definitions.IRSwaps import CURVE_DEFINITIONS

RATESLIB_CURVE_DEFINITIONS: Dict[str, Dict[str, str]] = {
    "USD-SOFR-1D": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZXQ4R16245X", "QZPB5VSBGRCD"],
    },
    "USD-FEDFUNDS": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "USD-OIS": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },

    "CAD-CORRA": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "cad_irs",
        "NotionalCurrency": "cad",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act365f",
        "Calendar": "toronto",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },

    "EUR-ESTR": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "eur_irs",
        "NotionalCurrency": "eur",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "tgt",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },

    "JPY-TONAR": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "jpy_irs",
        "NotionalCurrency": "jpy",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act365f",
        "Calendar": "tyo",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    
}

for k in RATESLIB_CURVE_DEFINITIONS.keys():
    assert k in CURVE_DEFINITIONS, f"key {k} in 'RATESLIB_CURVE_DEFINITIONS' must exist in global 'CURVE_DEFINITIONS'"
