from typing import Dict
import rateslib as rl

from definitions.IRSwaps import CURVE_DEFINITIONS

RATESLIB_CURVE_DEFINITIONS: Dict[str, Dict[str, str]] = {
    "USD-SOFR-1D": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZXQ4R16245X", "QZPB5VSBGRCD"],
    },
    "USD-SOFR-1D-RISK": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZXQ4R16245X", "QZPB5VSBGRCD"],
    },
    "USD-FEDFUNDS": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir1",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "USD-OIS": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "USD-OIS-STIR": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs_lt_2y",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "USD-FEDFUNDS-RISK": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir1",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "USD-FEDFUNDS-1D-RISK": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir1",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "USD-OIS-RISK": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "USD-OIS-STIR-RISK": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "usd_irs_lt_2y",
        "ReferenceRate2": "usd_stir",
        "ReferenceRate3": "usd_stir1",
        "NotionalCurrency": "usd",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "nyc",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "CAD-CORRA": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "cad_irs",
        "ReferenceRate2": "cad_irs",
        "ReferenceRate3": "cad_irs",
        "NotionalCurrency": "cad",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act365f",
        "Calendar": "tro",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    "EUR-ESTR": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "eur_irs",
        "ReferenceRate2": "eur_stir",
        "ReferenceRate3": "eur_stir1",
        "NotionalCurrency": "eur",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "tgt",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    "JPY-TONAR": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "jpy_irs",
        "ReferenceRate2": "jpy_irs",
        "ReferenceRate3": "jpy_irs",
        "NotionalCurrency": "jpy",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act365f",
        "Calendar": "tyo",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    "JPY-TONA": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "jpy_irs",
        "ReferenceRate2": "jpy_irs",
        "ReferenceRate3": "jpy_irs",
        "NotionalCurrency": "jpy",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act365f",
        "Calendar": "tyo",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    "GBP-SONIA": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "gbp_irs",
        "ReferenceRate2": "gbp_stir",
        "ReferenceRate3": "gbp_stir",
        "NotionalCurrency": "gbp",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act365f",
        "Calendar": "ldn",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 0,
        "SettlementDays": 0,
        "SDR_UPIs": [],
    },
    "CHF-SARON": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "chf_irs",
        "ReferenceRate2": "chf_irs",
        "ReferenceRate3": "chf_irs",
        "NotionalCurrency": "chf",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "days",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "act360",
        "Calendar": "zur",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    "EUR-EURIBOR-3M": {
        "UseCase": "Fixed_Float_IBOR",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "eur_irs",
        "ReferenceRate2": "eur_stir3",
        "ReferenceRate3": "eur_stir3",
        "NotionalCurrency": "eur",
        "ReferenceRateTermValue": 3,
        "ReferenceRateTermUnit": "months",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "30e360",
        "Calendar": "tgt",
        "BusinessConvention": "mf",
        "PaymentFrequency": "1y",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
}
