import datetime
from abc import ABC
from typing import Any, Optional

from Query.Base._GenericPricable import _GenericPricable
from Query.Base._GenericPricer import _GenericPricer
from Query.STIRFutureOptions._STIRFutureOptionGenericPricable import _STIRFutureOptionGenericPricable


class _STIRFutureOptionGenericPricer(_GenericPricer[_GenericPricable], ABC):
    def id(self) -> str: ...
    def symbol(self) -> str: ...
    def right(self) -> str: ...
    def underlying_symbol(self) -> str: ...
    def strike(self) -> float: ...
    def quote_timestamp(self) -> datetime.datetime: ...
    def expiry_date(self) -> datetime.date: ...

    def price(self) -> float: ...
    def model_price(self) -> float: ...
    def iv_normal(self) -> float: ...
    def iv_normal_bps(self) -> float: ...
    def delta(self) -> float: ...
    def gamma(self) -> float: ...
    def vega(self) -> float: ...
    def theta(self) -> float: ...
    def discount(self) -> float: ...
    def forward(self) -> float: ...
    def meta(self) -> Any: ...

    def resolve_pricable(
        self,
        priceable: _STIRFutureOptionGenericPricable,
        risk_weight: Optional[float] = None,
    ) -> _STIRFutureOptionGenericPricable: ...
