from enum import Enum


class QuikVolValueType(Enum):
    ATM = 0, ["IsVolType"]
    Call = 5, ["IsVolType"]
    Put = 6, ["IsVolType"]
    CallSkew = 9, ["IsVolDiffType"]
    PutSkew = 10, ["IsVolDiffType"]
    Butterfly = 13, ["IsVolDiffType"]
    RiskReversal = 12, ["IsVolDiffType"]
    Shift = 35, ["IsVolDiffType", "IsShiftOrSlide"]
    Slide = 36, ["IsVolDiffType", "IsShiftOrSlide"]
    CallRatio = 7, ["IsVolRatioType"]
    PutRatio = 8, ["IsVolRatioType"]
    ABPV = 1, ["IsBPVolType"]
    DBPV = 2, ["IsBPVolType"]
    Future = 16, ["IsFutureType"]
    HistVol5D = 17, ["IsHistoricalVol", "IsVolType"]
    HistVol10D = 18, ["IsHistoricalVol", "IsVolType"]
    HistVol20D = 19, ["IsHistoricalVol", "IsVolType"]
    HistVol30D = 20, ["IsHistoricalVol", "IsVolType"]
    HistVol60D = 21, ["IsHistoricalVol", "IsVolType"]
    ATMPrice = 23, ["IsPremiumType"]
    CallPrice = 26, ["IsPremiumType"]
    PutPrice = 27, ["IsPremiumType"]
    CallRatioPrice = 28, ["IsPremiumType", "IsVolRatioType"]
    PutRatioPrice = 29, ["IsPremiumType", "IsVolRatioType"]
    CallSkewPrice = 30, ["IsPremiumType", "IsVolDiffType"]
    PutSkewPrice = 31, ["IsPremiumType", "IsVolDiffType"]
    RiskReversalPrice = 32, ["IsPremiumType", "IsVolDiffType"]
    ButterflyPrice = 33, ["IsPremiumType", "IsVolDiffType"]
    Return = 37, ["IsReturnType"]
    VolByStrike = 38, ["IsVolType"]
    PriceByStrike = 39, ["IsPremiumType"]

