"""The findings-table generator is the provenance guarantee, so it gets tests.

The property that matters is not formatting: it is that a gate which did not run can
never be mistaken for a gate that passed. A missing artifact must be loud, an EMPTY
artifact must be distinguishable from a missing one, and truncation must announce
itself.
"""
import importlib.util
import os

import pandas as pd
import pytest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SPEC = importlib.util.spec_from_file_location(
    "render_findings_tables", os.path.join(REPO, "scripts", "render_findings_tables.py"))
R = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(R)


def _write(d, name, frame):
    frame.to_csv(os.path.join(str(d), f"{name}.csv"), index=False)


@pytest.fixture()
def results(tmp_path):
    _write(tmp_path, "verdicts", pd.DataFrame(
        [{"gate": "G1", "pass": True, "headline": "clean"}]))
    _write(tmp_path, "g1_audits", pd.DataFrame(
        [{"audit": "future_poison", "pass": True, "max_future_prints": 400}]))
    return tmp_path


def test_a_missing_required_artifact_is_loud_and_fails_check(results):
    md, missing = R.render(str(results))
    assert "REQUIRED ARTIFACT MISSING" in md
    assert "g3_horse_race_FUTURES" in missing
    assert R.main(["--results", str(results), "--check"]) == 1


def test_check_passes_only_when_every_required_artifact_exists(results):
    for name in [s[0] for s in R.SECTIONS if s[2]]:
        _write(results, name, pd.DataFrame([{"x": 1}]))
    assert R.main(["--results", str(results), "--check"]) == 0


def test_an_empty_artifact_reads_differently_from_a_missing_one(results):
    """"The stage ran and found nothing" and "the stage never ran" are different
    claims, and a report that conflates them is unreadable."""
    _write(results, "g4_conditioning", pd.DataFrame(columns=["split", "t"]))
    md, _ = R.render(str(results))
    assert "is empty — the stage ran and produced no rows" in md
    assert "g4_conditioning.csv` is absent" not in md


def test_an_absent_optional_artifact_is_not_reported_as_a_result(results):
    md, missing = R.render(str(results))
    assert "g2_lead_lag_summary_FED_FUNDS" not in missing
    assert "it is NOT a result" in md


def test_every_rendered_table_names_its_source_file(results):
    md, _ = R.render(str(results))
    assert md.count("_Source: `") >= 2
    assert "_Source: `g1_audits.csv` (1 rows)._" in md


def test_truncation_announces_itself(results):
    _write(results, "g4_league", pd.DataFrame(
        {"variant": [f"v{i}" for i in range(500)], "t": range(500)}))
    md, _ = R.render(str(results))
    assert "more in the CSV" in md
    assert "truncated for length only" in md


def test_the_header_says_the_file_is_generated(results):
    md, _ = R.render(str(results))
    assert md.splitlines()[0].startswith("<!-- GENERATED by")


def test_floats_keep_four_decimals_where_a_sign_flip_would_matter(results):
    _write(results, "g4_placebos", pd.DataFrame(
        [{"placebo": "none (reference)", "mean": -0.00012345, "t": 1.23456}]))
    md, _ = R.render(str(results))
    assert "-0.0001" in md and "1.2346" in md


def test_missing_results_dir_is_an_error_not_an_empty_report(tmp_path):
    assert R.main(["--results", str(tmp_path / "nope")]) == 2
