r"""Hermetic tests for the Citi Velocity OIS curve builders.

Covers ``MDP/CitiVelocityExcel/curves/``: the per-currency convention table
(``conventions.py``), the rateslib and QuantLib builders (``rl_builder.py``,
``ql_builder.py``) and the par-grid fetch/snapshot layer (``par_grid.py``).

Nothing here needs Excel, a network or a database. The transport is
:class:`MDP.CitiVelocityExcel.testing.FakeExcelApp`; the market data is a
**self-consistent synthetic par grid** built the way ``curves/_smoke.py`` builds
it - a smooth analytic discount curve is chosen, the 44 Velocity par swaps are
priced off it in each currency's own conventions, and those par rates are fed
back to the builders. A correct builder returns a curve that reprices its own
inputs.

What that does and does not prove
---------------------------------
It proves the solve converges and pins its own instruments, and - because the
grid is generated by *rateslib* and one arm of the check reprices it with
*QuantLib* - that the two independent libraries agree about frequency, day
count, payment lag, end-of-month and pillar placement. It does **not** prove the
conventions match the market: the rateslib reprice arm in particular is weakly
circular (the calibrating swap and the grid come from the same ``_make_irs``),
so a wrong day count would cancel out of it. That arm is a convergence check,
not a convention check, and its docstring says so. For the six
``market_standard`` currencies (DKK ILS MXN SGD THB ZAR) nothing hermetic could
establish correctness against the market, and MXN's 28-day Fondeo roll is
knowingly approximated by a monthly schedule.

Several tests are paired with a MUTATION CHECK: the same input is run through a
deliberately-wrong variant and the test asserts the wrong one produces a
different, wrong answer. A round trip that would pass against a metric returning
zeros is not a test, and this package's own history says so - a proxy calendar
would have misdated every ILS roll while every reprice check still tied out.
"""

from __future__ import annotations

import datetime
import functools
import inspect
import math
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import pytest
import QuantLib as ql
import rateslib as rl

from MDP.CitiVelocityExcel.catalog import CitiVeloCatalog
from MDP.CitiVelocityExcel.com_client import DEFAULT_CHUNK_SIZE, CitiVelocityExcelClient
from MDP.CitiVelocityExcel.curves.conventions import (
    CITI_OIS_CONVENTIONS,
    conventions_for,
    rl_calendar_from_quantlib,
    supported_indices,
)
from MDP.CitiVelocityExcel.curves.par_grid import (
    fetch_par_grid,
    par_grid_snapshot,
    tenor_columns_from_tags,
)
from MDP.CitiVelocityExcel.curves.ql_builder import (
    END_OF_MONTH_BY_INDEX,
    PAYMENT_LAG_BY_INDEX,
    build_ql_ois_curve,
    ql_forward_rate,
    ql_par_reprice_errors_bp,
)
from MDP.CitiVelocityExcel.curves.rl_builder import (
    _as_ref_date,
    _make_irs,
    _prev_business_day,
    build_rl_ois_curve,
    build_rl_ois_curve_from_quotes,
    end_of_month_for,
    forward_rate,
    par_reprice_errors_bp,
    payment_lag_for,
)
from MDP.CitiVelocityExcel.errors import UnknownTagError
from MDP.CitiVelocityExcel.tags import OIS_INDICES
from MDP.CitiVelocityExcel.testing import FakeExcelApp, FakeVelocityData

#: The Velocity OIS tenor axis, straight from the harvested catalog (44 tokens).
TENORS: List[str] = CitiVeloCatalog.default().tenors("RATES.OIS.USD_SOFR.PAR")

#: A Wednesday, so nothing is masked by an accidental weekend roll.
REF_DATE = datetime.date(2026, 8, 5)

#: The default currency set. USD/EUR are the annual ACT/360 majors, GBP is the
#: only T+0 settle in the table, CAD is the only semi-annual one among the four.
DEFAULT_CURRENCIES = ["USD_SOFR", "EUR_EUROSTR", "GBP_SONIA", "CAD_CORRA"]

#: The six currencies rateslib 2.1.1 ships no named spec for.
MARKET_STANDARD = {"DKK_TNDKK", "ILS_SHIR", "MXN_T_FONDEO", "SGD_SORA", "THB_THOR", "ZAR_ZARONIA"}

#: Reprice/agreement tolerance in basis points. Measured residuals sit ~5x
#: inside it (rateslib ~2e-3 bp, QuantLib ~2e-9 bp) and the cross-backend
#: forward gap collapses to ~1e-5 bp when the solver tolerance is tightened,
#: which is how we know the residual is solver noise and not a convention gap.
REPRICE_TOL_BP = 0.01


# ------------------------------------------------------------------ #
#                              fixtures                              #
# ------------------------------------------------------------------ #


@pytest.fixture(autouse=True)
def _restore_ql_evaluation_date():
    """No test in this module may leak QuantLib's process-global evaluation date.

    ``ql.Settings.instance().evaluationDate`` is global and every
    ``RelativeDateRateHelper`` observes it; a test that left it moved would
    silently redate curves built by every later test in the same process.
    """
    saved = ql.Settings.instance().evaluationDate
    yield
    ql.Settings.instance().evaluationDate = saved


def _zero(t: float) -> float:
    """A smooth Nelson-Siegel-shaped continuously-compounded zero curve."""
    if t <= 0:
        return 0.042
    tau = 3.0
    a = (1.0 - math.exp(-t / tau)) / (t / tau)
    return 0.030 + 0.015 * a + 0.010 * (a - math.exp(-t / tau))


@functools.lru_cache(maxsize=24)
def _synthetic_par_grid(citi_index: str) -> Tuple[Tuple[str, float], ...]:
    """Price the 44 Velocity par swaps off a known curve, in this ccy's conventions.

    Cached because the truth curve carries 660 monthly nodes and pricing 44
    swaps off it costs ~0.1s, which the sweep would otherwise pay per test.
    Returns an immutable pair sequence; callers make their own dict.
    """
    conv = conventions_for(citi_index)
    cal = conv.rl_calendar_object()
    ref = _prev_business_day(_as_ref_date(REF_DATE), cal)
    spot = cal.add_bus_days(ref, int(conv.spot_lag), True)

    nodes = {ref: 1.0}
    for m in range(1, 12 * 55 + 1):
        d = rl.add_tenor(ref, f"{m}M", "f", cal)
        t = (d - ref).days / 365.0
        nodes[d] = math.exp(-_zero(t) * t)
    truth = rl.Curve(
        nodes=nodes,
        id="TRUTH",
        convention=conv.convention,
        calendar=cal,
        modifier="mf",
        interpolation="log_linear",
    )
    return tuple(
        (
            tenor,
            float(
                _make_irs(
                    conv=conv,
                    calendar=cal,
                    effective=spot,
                    tenor=tenor,
                    curve_id="TRUTH",
                    fixed_rate=0.0,
                ).rate(curves=truth)
            ),
        )
        for tenor in TENORS
    )


def _par(citi_index: str = "USD_SOFR") -> Dict[str, float]:
    """A fresh, mutable copy of one currency's synthetic par grid."""
    return dict(_synthetic_par_grid(citi_index))


@pytest.fixture()
def usd_par() -> Dict[str, float]:
    return _par("USD_SOFR")


def _velocity_par_data(citi_index: str = "USD_SOFR") -> Tuple[FakeVelocityData, pd.DatetimeIndex]:
    """A fake add-in serving the whole 44-tenor PAR grid at hourly stamps."""
    stamps = pd.date_range("2026-07-27 09:00", periods=6, freq="h")
    tags = [f"RATES.OIS.{citi_index}.PAR.{t}" for t in TENORS]
    data = FakeVelocityData(
        series={
            tag: pd.Series([4.0 + 0.001 * i + 0.01 * j for j in range(len(stamps))], index=stamps)
            for i, tag in enumerate(tags)
        }
    )
    return data, stamps


def _fake_client(data: FakeVelocityData) -> Tuple[CitiVelocityExcelClient, FakeExcelApp]:
    app = FakeExcelApp(data, pending_reads=0)
    client = CitiVelocityExcelClient(app=app, poll_interval=0.0, drain_seconds=0.0)
    return client, app


@pytest.fixture()
def par_grid_frame() -> pd.DataFrame:
    """A fetched par grid: 6 hourly rows x 44 tenors, straight off the fake add-in."""
    data, _ = _velocity_par_data()
    client, _ = _fake_client(data)
    try:
        return fetch_par_grid(client=client, citi_index="USD_SOFR", freq="HOURLY", period="1W")
    finally:
        client.close()


def _rl(par_rates: Dict[str, float], citi_index: str = "USD_SOFR", **kw):
    return build_rl_ois_curve(par_rates=par_rates, ref_date=REF_DATE, citi_index=citi_index, **kw)


def _ql(par_rates: Dict[str, float], citi_index: str = "USD_SOFR", **kw):
    return build_ql_ois_curve(par_rates=par_rates, ref_date=REF_DATE, citi_index=citi_index, **kw)


# ------------------------------------------------------------------ #
#                        the convention table                        #
# ------------------------------------------------------------------ #


def test_every_citi_ois_index_token_has_conventions():
    """All 20 harvested OIS tokens are covered, and nothing extra is invented.

    ``tags.OIS_INDICES`` is the list the add-in itself produced. Generate-and-test
    over plausible spellings got ``EUR_EUROSTR`` and ``USD_FEDFUND`` wrong and
    missed six curves outright, so the table is checked against the harvest
    rather than against a hand-written list.
    """
    assert len(OIS_INDICES) == 20
    assert set(supported_indices()) == set(OIS_INDICES)
    for token in OIS_INDICES:
        assert CITI_OIS_CONVENTIONS[token].citi_index == token


@pytest.mark.parametrize("citi_index", sorted(OIS_INDICES))
def test_every_ql_calendar_and_index_factory_constructs(citi_index):
    """The factories are lazy, so a typo'd class name would surface only at build.

    Six of the indices (SORA NOWA STINA TNDKK SHIR T_FONDEO) have no QuantLib
    class at all and are assembled from ``ql.OvernightIndex``; this walks every
    one of the twenty so a missing class is a test failure rather than a
    currency that silently cannot be built.
    """
    conv = CITI_OIS_CONVENTIONS[citi_index]
    calendar = conv.ql_calendar()
    assert isinstance(calendar, ql.Calendar)

    index = conv.ql_index(ql.YieldTermStructureHandle())
    assert isinstance(index, ql.OvernightIndex)
    assert isinstance(index.fixingCalendar(), ql.Calendar)
    # OISRateHelper takes the FIXED leg day count from the index, so a mismatch
    # here would accrue the fixed leg on the wrong basis with nothing complaining.
    assert index.dayCounter().name() == {
        "act360": "Actual/360",
        "act365f": "Actual/365 (Fixed)",
    }[conv.convention]


@pytest.mark.parametrize(
    "citi_index", sorted(t for t in OIS_INDICES if CITI_OIS_CONVENTIONS[t].rl_spec)
)
def test_specd_currencies_agree_with_rateslib(citi_index):
    """rateslib's named spec is the authority for the fourteen it ships one for.

    Frequency, day count, calendar and payment lag are all read back out of
    ``rl.defaults.spec`` and compared against the table, so a rateslib upgrade
    that changes a spec fails here rather than quietly repricing every
    long-dated curve in that currency.
    """
    conv = CITI_OIS_CONVENTIONS[citi_index]
    spec = rl.defaults.spec[conv.rl_spec]

    assert conv.fixed_frequency == spec["frequency"]
    assert conv.convention == spec["convention"]
    assert conv.rl_calendar == spec["calendar"]
    assert PAYMENT_LAG_BY_INDEX[citi_index] == spec["payment_lag"]
    assert END_OF_MONTH_BY_INDEX[citi_index] == spec["eom"]

    # The accessors re-read the spec themselves and raise on a divergence.
    assert payment_lag_for(citi_index) == spec["payment_lag"]
    assert end_of_month_for(citi_index) == spec["eom"]
    assert conv.approximate is False
    assert conv.provenance == "rateslib_spec"


def test_the_six_unspecd_currencies_are_flagged_and_explained():
    """No rateslib spec means ``approximate=True`` and a note saying what is approximate.

    Silently shipping market-standard conventions as if they were
    library-supplied is the failure this guards: the six are exactly DKK, ILS,
    MXN, SGD, THB and ZAR, and MXN in particular approximates a 28-day Fondeo
    roll with a monthly schedule.
    """
    flagged = {t for t in OIS_INDICES if CITI_OIS_CONVENTIONS[t].approximate}
    assert flagged == MARKET_STANDARD
    for token in sorted(MARKET_STANDARD):
        conv = CITI_OIS_CONVENTIONS[token]
        assert conv.rl_spec is None
        assert conv.rl_calendar is None, "an unspec'd currency must not borrow a proxy calendar"
        assert conv.provenance == "market_standard"
        assert conv.note.strip(), f"{token} is approximate but says nothing about what"
    assert "28-DAY" in CITI_OIS_CONVENTIONS["MXN_T_FONDEO"].note.upper()


def test_unknown_index_raises_and_suggests():
    with pytest.raises(UnknownTagError) as excinfo:
        conventions_for("EUR_ESTR")  # the plausible spelling; the real one is EUR_EUROSTR
    assert "EUR_EUROSTR" in str(excinfo.value)


# ------------------------------------------------------------------ #
#                             calendars                              #
# ------------------------------------------------------------------ #


def test_ils_calendar_trades_sunday_to_thursday():
    """ILS's week mask is Friday/Saturday, not Saturday/Sunday.

    2026-08-07/08/09 are a Friday, a Saturday and a Sunday. Israel trades
    Sunday-Thursday, so the Sunday is a business day and the Friday is not.
    """
    cal = conventions_for("ILS_SHIR").rl_calendar_object()
    friday = datetime.datetime(2026, 8, 7)
    saturday = datetime.datetime(2026, 8, 8)
    sunday = datetime.datetime(2026, 8, 9)
    assert friday.weekday() == 4 and saturday.weekday() == 5 and sunday.weekday() == 6

    assert cal.is_bus_day(sunday) is True
    assert cal.is_bus_day(friday) is False
    assert cal.is_bus_day(saturday) is False


def test_a_monday_friday_proxy_calendar_gets_the_israeli_week_backwards():
    """MUTATION CHECK for the refusal to substitute a proxy calendar.

    rateslib 2.1.1 ships 14 calendars and none of them is Israel. Substituting
    a Monday-Friday one - which is what every shipped calendar is - inverts both
    ends of the week: it makes Friday a business day and Sunday a holiday. Every
    roll on the curve would move, and no reprice check would notice, because the
    grid and the curve would both be wrong the same way. That is why
    ``rl_calendar_from_quantlib`` materialises QuantLib's real Israel holidays
    against an explicit ``(4, 5)`` weekend instead.
    """
    conv = conventions_for("ILS_SHIR")
    real = conv.rl_calendar_object()
    proxy = rl_calendar_from_quantlib(conv.ql_calendar())  # default weekend == Sat/Sun

    friday = datetime.datetime(2026, 8, 7)
    sunday = datetime.datetime(2026, 8, 9)
    assert real.is_bus_day(sunday) and not proxy.is_bus_day(sunday)
    assert proxy.is_bus_day(friday) and not real.is_bus_day(friday)

    # ... and the cost is moved DATES, not just a moved flag. Measured from
    # 2026-08-05: the T+2 spot date moves by two days (2026-08-09 under the real
    # Sun-Thu week, 2026-08-07 under the proxy), and 8 of the 17 standard tenors
    # land on a different maturity. Note a 1Y happens NOT to move - which is why
    # this test sweeps the axis instead of asserting on one convenient tenor.
    ref = _as_ref_date(REF_DATE)
    assert rl.add_tenor(ref, "2B", "f", real) != rl.add_tenor(ref, "2B", "f", proxy)

    axis = ["1M", "2M", "3M", "6M", "9M", "1Y", "18M", "2Y", "3Y", "4Y", "5Y", "7Y",
            "10Y", "15Y", "20Y", "30Y", "40Y"]
    moved = [
        t for t in axis
        if rl.add_tenor(ref, t, "mf", real) != rl.add_tenor(ref, t, "mf", proxy)
    ]
    assert len(moved) >= 6, f"only {len(moved)} of {len(axis)} tenors moved: {moved}"


def test_synthesised_calendars_carry_real_holidays_not_just_a_weekend_mask():
    """A calendar with the right weekend but no holidays would still misdate rolls."""
    conv = conventions_for("ZAR_ZARONIA")
    cal = conv.rl_calendar_object()
    # 2027-01-01 is a Friday and a South African public holiday.
    new_year = datetime.datetime(2027, 1, 1)
    assert new_year.weekday() == 4
    assert cal.is_bus_day(new_year) is False


# ------------------------------------------------------------------ #
#                  self-consistency, both backends                   #
# ------------------------------------------------------------------ #


@pytest.mark.parametrize("citi_index", DEFAULT_CURRENCIES)
def test_rateslib_curve_reprices_its_own_calibration_swaps(citi_index):
    """The rateslib solve pins every one of its 44 instruments to < 0.01 bp.

    Weakly circular by construction, and deliberately so: the synthetic grid is
    priced with the same ``_make_irs`` the builder calibrates with, so a wrong
    day count or payment lag cancels out and this test would not see it. What it
    does see is a solve that did not converge, a misplaced pillar, or a node
    that ended up on a different date from the swap that was supposed to pin it
    - which is what an unconverged curve looks like from the outside. The
    convention check is the QuantLib arm below, which reprices the same grid
    with an independent library.
    """
    rlc = _rl(_par(citi_index), citi_index)
    errors = par_reprice_errors_bp(rlc)
    assert len(errors) == len(TENORS)
    assert float(errors.abs().max()) < REPRICE_TOL_BP
    assert rlc.meta["citi_index"] == citi_index
    assert rlc.rl_pricing_curve_solver.result["status"] == "SUCCESS"


@pytest.mark.parametrize("citi_index", DEFAULT_CURRENCIES)
def test_quantlib_curve_reprices_the_rateslib_generated_grid(citi_index):
    """QuantLib recovers a grid rateslib priced, to < 0.01 bp.

    This is the arm with teeth on conventions: the par rates come out of
    ``rl.IRS`` and go back in through ``ql.OISRateHelper``/``MakeOIS``. The two
    libraries share no code, so a disagreement about frequency, day count,
    payment lag, end-of-month or pillar placement shows up here as a reprice
    error far outside tolerance rather than cancelling out.
    """
    par = _par(citi_index)
    qlc = _ql(par, citi_index)
    errors = ql_par_reprice_errors_bp(qlc, par)
    assert len(errors) == len(TENORS)
    assert float(errors.abs().max()) < REPRICE_TOL_BP
    assert qlc.citi_index == citi_index


@pytest.mark.parametrize("citi_index", DEFAULT_CURRENCIES)
def test_both_backends_anchor_on_the_same_rolled_reference_date(citi_index):
    """A weekend snapshot rolls BACK to the prior business day, identically in both.

    2026-08-08 is a Saturday. GBP settles T+0 and CAD T+1, so if the two
    builders rolled differently the whole curve would shift and every
    cross-backend comparison below would be measuring the wrong thing.
    """
    saturday = datetime.date(2026, 8, 8)
    par = _par(citi_index)
    rlc = build_rl_ois_curve(par_rates=par, ref_date=saturday, citi_index=citi_index)
    qlc = build_ql_ois_curve(par_rates=par, ref_date=saturday, citi_index=citi_index)
    assert rlc.meta["ref_date"].date() == qlc.reference_date
    assert qlc.reference_date < saturday


def test_gbp_settles_t_plus_zero_and_cad_t_plus_one():
    """The spot lag is not uniform, and SONIA is the one that catches people out."""
    usd = _rl(_par("USD_SOFR"), "USD_SOFR")
    gbp = _rl(_par("GBP_SONIA"), "GBP_SONIA")
    cad = _rl(_par("CAD_CORRA"), "CAD_CORRA")
    assert gbp.meta["spot"] == gbp.meta["ref_date"]
    assert usd.meta["spot"] > usd.meta["ref_date"]
    assert cad.meta["spot"] > cad.meta["ref_date"]
    assert conventions_for("CAD_CORRA").fixed_frequency == "s"  # semi-annual, alone among the four


# ------------------------------------------------------------------ #
#                cross-backend agreement, USD_SOFR                   #
# ------------------------------------------------------------------ #


@pytest.mark.parametrize("forward,tenor", [("5Y", "5Y"), ("10Y", "10Y")])
def test_rateslib_and_quantlib_agree_on_usd_sofr_forwards(forward, tenor):
    """The two backends price the same forward swap to within **0.01 bp**.

    Measured at the default solver tolerance: 2.0e-5 bp on the 5Yx5Y and
    3.8e-4 bp on the 10Yx10Y, i.e. 25x-500x inside the stated bound. The bound
    is 0.01 bp rather than machine precision because rateslib's Levenberg-
    Marquardt solve stops at ``func_tol=1e-9``, and the test below shows the gap
    collapsing with that tolerance - which is how we know the residual is solver
    noise and not a convention difference. USD_SOFR is chosen because rateslib's
    ``nyc`` and QuantLib's SOFR fixing calendar put all 44 pillars on the same
    days; for AUD they do not, and there the gap is 0.067 bp of calendar data,
    not of curve.
    """
    par = _par("USD_SOFR")
    rl_rate = forward_rate(_rl(par), forward=forward, tenor=tenor)
    ql_rate = ql_forward_rate(_ql(par), forward=forward, tenor=tenor)
    assert abs(rl_rate - ql_rate) * 100.0 < REPRICE_TOL_BP


def test_the_cross_backend_gap_collapses_with_the_solver_tolerance():
    """Teeth for the tolerance above: tighten the solve and the gap goes away.

    If the ~4e-4 bp residual were a convention difference it would be invariant
    to ``func_tol``. At ``func_tol=1e-14`` it drops below 1e-3 bp, so it is the
    solver stopping, not the two libraries disagreeing about the instrument.
    """
    par = _par("USD_SOFR")
    qlc = _ql(par)
    loose = _rl(par)
    tight = _rl(par, func_tol=1e-14, conv_tol=1e-16)

    gaps = {}
    for label, rlc in (("loose", loose), ("tight", tight)):
        gaps[label] = max(
            abs(forward_rate(rlc, forward=f, tenor=t) - ql_forward_rate(qlc, forward=f, tenor=t))
            * 100.0
            for f, t in (("5Y", "5Y"), ("10Y", "10Y"))
        )
    assert gaps["tight"] < 1e-3
    assert gaps["tight"] < gaps["loose"]


# ------------------------------------------------------------------ #
#            mutation checks on the measurement itself               #
# ------------------------------------------------------------------ #


def _zero_returning_reprice_errors_bp(_curve) -> pd.Series:
    """A repricer that always reports a perfect fit. The thing being mutated in."""
    return pd.Series({t: 0.0 for t in TENORS}, name="reprice_error_bp", dtype=float)


def test_a_reprice_metric_that_returns_zeros_would_pass_the_round_trip(usd_par):
    """MUTATION CHECK for the self-consistency tests above.

    ``build a curve, reprice its own inputs, assert the error is small`` passes
    unconditionally against a metric that returns zeros. So the round trip alone
    proves nothing, and the two tests that follow are what give it teeth: the
    real metrics have to *move* when their input moves.
    """
    rlc = _rl(usd_par)
    broken = _zero_returning_reprice_errors_bp(rlc)
    assert float(broken.abs().max()) < REPRICE_TOL_BP  # the naive assertion, passing on a lie
    assert float(par_reprice_errors_bp(rlc).abs().max()) < REPRICE_TOL_BP


def test_quantlib_reprice_metric_reports_the_bump_it_is_given(usd_par):
    """Repriced against a grid bumped 1 bp on every tenor, the metric reads 1 bp.

    This is the direct teeth for :func:`ql_par_reprice_errors_bp`: it is fed a
    quote set that is deliberately NOT the one the curve was built from, and
    must report the difference on every one of the 44 tenors.
    """
    qlc = _ql(usd_par)
    bumped = {t: v + 0.01 for t, v in usd_par.items()}
    errors = ql_par_reprice_errors_bp(qlc, bumped).abs()
    assert float(errors.min()) == pytest.approx(1.0, abs=0.05)
    assert float(errors.max()) == pytest.approx(1.0, abs=0.05)
    assert float(_zero_returning_reprice_errors_bp(qlc).abs().max()) == 0.0


def test_a_five_bp_quote_bump_moves_the_rebuilt_par_rate_by_five_bp(usd_par):
    """MUTATION CHECK on the builder: the curve must respond to its inputs.

    A builder that ignored ``par_rates`` and returned a flat curve, or a
    ``par_reprice_errors_bp`` that measured the quote against itself, would both
    pass every round trip above. Bumping the 10Y quote by 5 bp and reading the
    rebuilt curve's own 10Y par rate back out is what separates them: it must
    move by 5 bp, and only at that tenor's own quote.
    """
    shifted = dict(usd_par)
    shifted["10Y"] = usd_par["10Y"] + 0.05

    base = _rl(usd_par)
    bumped = _rl(shifted)
    moved = (
        forward_rate(bumped, forward="0D", tenor="10Y")
        - forward_rate(base, forward="0D", tenor="10Y")
    ) * 100.0
    assert moved == pytest.approx(5.0, abs=0.05)

    # The 1Y sits entirely in front of the bumped node, so it must not move.
    unmoved = (
        forward_rate(bumped, forward="0D", tenor="1Y")
        - forward_rate(base, forward="0D", tenor="1Y")
    ) * 100.0
    assert abs(unmoved) < REPRICE_TOL_BP


# ------------------------------------------------------------------ #
#                    guards: raise, never degrade                    #
# ------------------------------------------------------------------ #


@pytest.mark.parametrize("build", [build_rl_ois_curve, build_ql_ois_curve], ids=["rl", "ql"])
def test_too_few_tenors_raises(build):
    """A 1-tenor snapshot solves trivially and means nothing, so it is refused."""
    with pytest.raises(ValueError) as excinfo:
        build(par_rates={"5Y": 4.0}, ref_date=REF_DATE)
    assert "min_tenors" in str(excinfo.value)


@pytest.mark.parametrize("build", [build_rl_ois_curve, build_ql_ois_curve], ids=["rl", "ql"])
def test_all_nan_grid_raises(build):
    """An all-NaN column once shipped as 'success' in this repo. Never again."""
    with pytest.raises(ValueError) as excinfo:
        build(par_rates={t: float("nan") for t in TENORS}, ref_date=REF_DATE)
    assert "no usable par rates" in str(excinfo.value)


@pytest.mark.parametrize("build", [build_rl_ois_curve, build_ql_ois_curve], ids=["rl", "ql"])
def test_unknown_citi_index_raises(build, usd_par):
    with pytest.raises(UnknownTagError) as excinfo:
        build(par_rates=usd_par, ref_date=REF_DATE, citi_index="USD_LIBOR")
    assert "No curve conventions" in str(excinfo.value)


@pytest.mark.parametrize("build", [build_rl_ois_curve, build_ql_ois_curve], ids=["rl", "ql"])
def test_two_tenors_on_one_maturity_raises(build):
    """``1Y`` and ``12M`` are the same swap, and a duplicated node is singular.

    A dict cannot hold a duplicated key, so the collision has to arrive as two
    spellings of one maturity - which is exactly how it arrives in practice when
    a caller merges two tenor axes. Discovered late it is a singular Jacobian or
    a failed bootstrap with no currency named; discovered here it names the date
    and both tenors.
    """
    colliding = {"1Y": 4.0, "12M": 4.0, "2Y": 3.9, "5Y": 3.8, "10Y": 3.9}
    with pytest.raises(ValueError) as excinfo:
        build(par_rates=colliding, ref_date=REF_DATE)
    message = str(excinfo.value)
    assert "collide" in message
    assert "1Y" in message and "12M" in message


def test_an_unconvergent_rateslib_solve_raises_instead_of_returning_the_curve():
    """A -5000% front quote breaks the solve, and the curve must NOT come back.

    rateslib reports ``FAILURE: max_iter breached ... f_val: nan`` and returns a
    Solver object regardless; the builder reads ``solver.result['status']`` and
    refuses. An unconverged curve prices everything downstream wrongly and
    silently, which is the exact shape of the NULL-risk incident this repo
    already has on record.
    """
    with pytest.raises(ValueError) as excinfo:
        build_rl_ois_curve(
            par_rates={"1Y": -5000.0, "2Y": 4.0, "5Y": 3.8, "10Y": 3.9}, ref_date=REF_DATE
        )
    message = str(excinfo.value)
    assert "status='FAILURE'" in message
    assert "not returned" in message.lower()


def test_a_failed_quantlib_bootstrap_raises_with_the_currency_named():
    """The bootstrap is forced inside the builder so the failure has context."""
    with pytest.raises(ValueError) as excinfo:
        build_ql_ois_curve(
            par_rates={"1Y": -5000.0, "2Y": 4.0, "5Y": 3.8, "10Y": 3.9}, ref_date=REF_DATE
        )
    assert "USD_SOFR" in str(excinfo.value)
    assert "bootstrap failed" in str(excinfo.value)


def test_unknown_interpolation_raises_and_names_the_supported_set(usd_par):
    with pytest.raises(ValueError) as excinfo:
        build_ql_ois_curve(
            par_rates=usd_par, ref_date=REF_DATE, interpolation="cubic_spline"
        )
    assert "unknown interpolation" in str(excinfo.value).lower()
    assert "log_linear" in str(excinfo.value)


def test_from_quotes_refuses_to_build_a_eur_grid_with_usd_conventions(usd_par):
    """Tag index vs ``citi_index`` disagreement is an error, not a silent choice."""
    quotes = {f"RATES.OIS.EUR_EUROSTR.PAR.{t}": v for t, v in usd_par.items()}
    with pytest.raises(ValueError) as excinfo:
        build_rl_ois_curve_from_quotes(quotes=quotes, ref_date=REF_DATE, citi_index="USD_SOFR")
    assert "citi_index" in str(excinfo.value)


def test_from_quotes_rejects_a_non_par_tag():
    with pytest.raises(ValueError) as excinfo:
        build_rl_ois_curve_from_quotes(
            quotes={"RATES.OIS.USD_SOFR.FWD.5Y.5Y": 4.0}, ref_date=REF_DATE
        )
    assert "PAR" in str(excinfo.value)


def test_from_quotes_builds_the_same_curve_as_the_tenor_keyed_call(usd_par):
    quotes = {f"RATES.OIS.USD_SOFR.PAR.{t}": v for t, v in usd_par.items()}
    from_quotes = build_rl_ois_curve_from_quotes(quotes=quotes, ref_date=REF_DATE)
    direct = _rl(usd_par)
    assert from_quotes.meta["tenors"] == direct.meta["tenors"]
    assert forward_rate(from_quotes, forward="5Y", tenor="5Y") == pytest.approx(
        forward_rate(direct, forward="5Y", tenor="5Y"), abs=1e-12
    )


# ------------------------------------------------------------------ #
#                 QuantLib evaluation-date hygiene                   #
# ------------------------------------------------------------------ #


def test_builder_restores_the_global_evaluation_date(usd_par):
    """The builder must leave ``ql.Settings`` exactly as it found it.

    The evaluation date is process-global. A bulk build that left it mutated
    silently redates every curve built afterwards in the same process - which
    has happened in this repo, and is why nothing in ``ql_builder`` sets the
    global without a ``finally``.
    """
    sentinel = ql.Date(15, 3, 2001)
    ql.Settings.instance().evaluationDate = sentinel
    _ql(usd_par)
    assert ql.Settings.instance().evaluationDate == sentinel


def test_the_returned_curve_does_not_move_when_the_global_date_moves(usd_par):
    """The returned curve is frozen onto its own pillars, so it is date-independent."""
    qlc = _ql(usd_par)
    probe = ql.Date(7, 8, 2036)

    before = qlc.curve.discount(probe)
    ql.Settings.instance().evaluationDate = ql.Date(5, 2, 2027)
    after = qlc.curve.discount(probe)
    assert abs(after - before) < 1e-15


def test_an_unfrozen_piecewise_curve_over_the_same_helpers_does_move(usd_par):
    """MUTATION CHECK for the freezing: the live bootstrap curve is NOT immune.

    ``OISRateHelper`` is a ``RelativeDateRateHelper`` - it observes
    ``Settings::evaluationDate`` and recomputes its dates whenever that global
    moves, so a ``Piecewise*`` curve built from them re-bootstraps against
    whatever the date happens to be when it is next queried. Building exactly
    that over the same helpers and moving the date six months shifts the 10Y
    discount factor by ~4.6e-3 (a few bp of 10Y zero). Without this test, the
    immunity assertion above could be passing because the probe is insensitive
    rather than because the curve is frozen.
    """
    qlc = _ql(usd_par)
    probe = ql.Date(7, 8, 2036)
    ref = ql.Date(REF_DATE.day, REF_DATE.month, REF_DATE.year)

    ql.Settings.instance().evaluationDate = ref
    live = ql.PiecewiseLogLinearDiscount(ref, list(qlc.helpers), ql.Actual360())
    live.enableExtrapolation()
    live_before = live.discount(probe)

    ql.Settings.instance().evaluationDate = ql.Date(5, 2, 2027)
    live_after = live.discount(probe)

    assert abs(live_after - live_before) > 1e-6
    # ... while the frozen curve, over the same helpers, did not budge at all.
    assert abs(qlc.curve.discount(probe) - qlc.curve.discount(probe)) == 0.0


# ------------------------------------------------------------------ #
#                       par grid: snapshotting                       #
# ------------------------------------------------------------------ #


def test_asof_is_the_default_snapshot_method():
    """The default is the only method that cannot look forward in time."""
    assert inspect.signature(par_grid_snapshot).parameters["method"].default == "asof"


def test_asof_takes_the_last_row_at_or_before_the_request(par_grid_frame):
    snap = par_grid_snapshot(par_grid_frame, "2026-07-27 11:30")
    assert snap.name == pd.Timestamp("2026-07-27 11:00")
    assert list(snap.index) == list(par_grid_frame.columns)


def test_nearest_does_look_forward_which_is_why_it_is_not_the_default(par_grid_frame):
    """MUTATION CHECK for the default: ``nearest`` is direction-unbounded.

    11:40 is nearer the 12:00 row than the 11:00 one, so ``nearest`` answers
    with a row from the future while ``asof`` does not. (11:30 would be an exact
    tie and would prove nothing.) A curve built from a future snapshot is not
    wrong in any way a test notices - it is wrong in a way a backtest notices,
    much later, as an implausibly good result. This repo measured ``nearest``
    answering a 00:05 request with a snapshot 55 minutes ahead of it.
    """
    when = pd.Timestamp("2026-07-27 11:40")
    near = par_grid_snapshot(par_grid_frame, when, method="nearest")
    late = par_grid_snapshot(par_grid_frame, when, method="asof")
    assert near.name > when > late.name
    assert near.name == pd.Timestamp("2026-07-27 12:00")


def test_exact_requires_the_timestamp_and_asof_refuses_to_reach_backwards(par_grid_frame):
    assert par_grid_snapshot(
        par_grid_frame, "2026-07-27 11:00", method="exact"
    ).name == pd.Timestamp("2026-07-27 11:00")
    with pytest.raises(ValueError):
        par_grid_snapshot(par_grid_frame, "2026-07-27 11:30", method="exact")
    with pytest.raises(ValueError):
        par_grid_snapshot(par_grid_frame, "2020-01-01")  # before the frame starts
    with pytest.raises(ValueError):
        par_grid_snapshot(par_grid_frame, "2026-07-27 11:00", method="closest")


def test_a_snapshot_builds_a_curve_straight_off(par_grid_frame):
    """``snap.name`` carries the row actually used, so it is also the ref date."""
    snap = par_grid_snapshot(par_grid_frame, "2026-07-27 11:30")
    rlc = build_rl_ois_curve(par_rates=snap, ref_date=snap.name, citi_index="USD_SOFR")
    assert float(par_reprice_errors_bp(rlc).abs().max()) < REPRICE_TOL_BP


# ------------------------------------------------------------------ #
#                    par grid: fetch (fake Excel)                    #
# ------------------------------------------------------------------ #


def test_the_whole_44_tenor_grid_is_one_cvtshist_call():
    """44 tags, one round trip - which is where ``DEFAULT_CHUNK_SIZE`` comes from.

    The add-in serves all 44 columns of a curve export in a single call, so a
    par grid must cost one call and not 44. A regression to per-tenor fetching
    would not fail any correctness assertion; it would just make an intraday
    grid unusably slow, so the call count is asserted directly.
    """
    assert DEFAULT_CHUNK_SIZE == len(TENORS) == 44
    data, _ = _velocity_par_data()
    client, app = _fake_client(data)
    try:
        frame = fetch_par_grid(client=client, citi_index="USD_SOFR", freq="HOURLY", period="1W")
    finally:
        client.close()

    formulas = app.formulas_for("CVTSHIST")
    assert len(formulas) == 1
    for tenor in TENORS:
        assert f"RATES.OIS.USD_SOFR.PAR.{tenor}" in formulas[0]
    assert len(frame.columns) == 44
    assert frame.index.name == "timestamp"
    assert frame.index.is_monotonic_increasing


def test_one_bad_tenor_costs_exactly_its_own_column():
    """``CVTSHIST`` degrades per column; losing one tenor must not lose the grid."""
    data, _ = _velocity_par_data()
    refused = TENORS[3]  # '3W'
    data.bad_tags = {f"RATES.OIS.USD_SOFR.PAR.{refused}"}

    client, app = _fake_client(data)
    try:
        frame = fetch_par_grid(client=client, citi_index="USD_SOFR", freq="HOURLY", period="1W")
    finally:
        client.close()

    assert len(app.formulas_for("CVTSHIST")) == 1, "a refusal must not trigger a retry storm"
    assert refused not in frame.columns
    assert list(frame.columns) == [t for t in TENORS if t != refused]
    assert not frame.isna().any().any()


def test_columns_come_back_in_maturity_order_not_lexical(par_grid_frame):
    """``2W`` before ``1M``, ``9Y`` before ``10Y``: sorted by maturity, not by string."""
    columns = list(par_grid_frame.columns)
    assert columns == tenor_columns_from_tags(columns)
    assert columns[:6] == ["1D", "1W", "2W", "3W", "1M", "2M"]
    assert columns.index("9Y") < columns.index("10Y")


def test_fetch_par_grid_with_no_client_and_no_cache_raises():
    with pytest.raises(ValueError) as excinfo:
        fetch_par_grid(client=None, citi_index="USD_SOFR")
    assert "client" in str(excinfo.value)


def test_period_and_cache_are_mutually_exclusive(tmp_path):
    """The cache keys coverage on absolute stamps and cannot reason about '1Y'."""
    from MDP.CitiVelocityExcel.cache import CitiVeloTagCache

    data, _ = _velocity_par_data()
    client, _ = _fake_client(data)
    try:
        with pytest.raises(ValueError) as excinfo:
            fetch_par_grid(
                client=client,
                citi_index="USD_SOFR",
                period="1Y",
                cache=CitiVeloTagCache(base_dir=tmp_path),
            )
    finally:
        client.close()
    assert "mutually exclusive" in str(excinfo.value)


# ------------------------------------------------------------------ #
#                        the whole table (slow)                      #
# ------------------------------------------------------------------ #


@pytest.mark.slow
@pytest.mark.parametrize("citi_index", sorted(OIS_INDICES))
def test_every_currency_builds_and_reprices_on_both_backends(citi_index):
    """All twenty curves, both backends, < 0.01 bp on their own inputs.

    Kept out of the fast gate because it is 20 currencies x 2 bootstraps x 44
    instruments (~16s wall). The default set above covers the four shapes that
    differ structurally; this one is the regression net for the other sixteen,
    including the six whose conventions are market standard rather than
    library-supplied.
    """
    par = _par(citi_index)
    rlc = build_rl_ois_curve(par_rates=par, ref_date=REF_DATE, citi_index=citi_index)
    qlc = build_ql_ois_curve(par_rates=par, ref_date=REF_DATE, citi_index=citi_index)
    assert float(par_reprice_errors_bp(rlc).abs().max()) < REPRICE_TOL_BP
    assert float(ql_par_reprice_errors_bp(qlc, par).abs().max()) < REPRICE_TOL_BP


@pytest.mark.slow
def test_cross_backend_forward_agreement_is_bounded_by_calendar_data():
    """Where the two libraries' holidays agree, the forwards agree to 0.01 bp.

    rateslib ships its own 14 calendars and QuantLib its own national ones, and
    nothing reconciles them: for AUD the disagreement moves five of the 44 swap
    maturities by a day, which is the entire 0.067 bp gap on that curve. That is
    calendar data, not a builder bug, so it is bounded loosely rather than
    asserted away - but every calendar-aligned currency is held to 0.01 bp, and
    the misaligned ones are still required to stay inside 0.5 bp, which is far
    tighter than any real convention error would be.
    """
    forwards = [("1Y", "1Y"), ("5Y", "5Y"), ("10Y", "10Y")]
    aligned, misaligned = {}, {}
    for citi_index in sorted(OIS_INDICES):
        par = _par(citi_index)
        rlc = build_rl_ois_curve(par_rates=par, ref_date=REF_DATE, citi_index=citi_index)
        qlc = build_ql_ois_curve(par_rates=par, ref_date=REF_DATE, citi_index=citi_index)
        with qlc.pinned():
            ql_pillars = {
                (d.year(), d.month(), d.dayOfMonth()) for d in (h.pillarDate() for h in qlc.helpers)
            }
        mismatches = [
            tenor
            for tenor, mat in rlc.meta["maturities"].items()
            if (mat.year, mat.month, mat.day) not in ql_pillars
        ]
        gap = max(
            abs(forward_rate(rlc, forward=f, tenor=t) - ql_forward_rate(qlc, forward=f, tenor=t))
            * 100.0
            for f, t in forwards
        )
        (misaligned if mismatches else aligned)[citi_index] = gap

    assert len(aligned) >= 15, f"unexpectedly many misaligned calendars: {sorted(misaligned)}"
    assert max(aligned.values()) < REPRICE_TOL_BP, aligned
    assert not misaligned or max(misaligned.values()) < 0.5, misaligned
