import datetime
from abc import ABC, abstractmethod
from typing import Any, Optional

from Query.Base._GenericPricable import _GenericPricable
from Query.Base._GenericPricer import _GenericPricer
from Query.FixedRateBonds._FixedRateBondGenericPricable import _FixedRateBondGenericPricable


class _FixedRateBondGenericPricer(_GenericPricer[_GenericPricable], ABC):

    def id(self) -> str: ...
    def reference_date(self) -> datetime.date: ...
    def calendar(self) -> Any: ...
    def calendar_advance(self, dt1: datetime.date, dt2: datetime.date) -> datetime.date: ...
    def meta(self) -> Any: ...

    def issue_date(self) -> datetime.date: ...
    def maturity_date(self) -> datetime.date: ...
    def coupon(self) -> float: ...
    def notional(self) -> float: ...
    def ytm(self) -> float: ...
    def dirty_price(self) -> float: ...
    def clean_price(self) -> float: ...
    def npv(self) -> float: ...
    def accured(self) -> float: ...
    def pv01(self) -> float: ...
    def mod_duration(self) -> float: ...
    def convexity(self) -> float: ...
    def time_to_maturity(self) -> float: ... 

    def resolve_pricable(self, frb: _FixedRateBondGenericPricable, risk_weight: Optional[float] = None) -> _FixedRateBondGenericPricable: ...

    def build_fixed_rate_bond(
        self,
        issue_date: Optional[datetime.date] = None,
        maturity_date: Optional[datetime.date] = None,
        coupon: Optional[float] = -0.00,
        notional: Optional[float] = None,
        bpv: Optional[float] = None,
    ) -> Any: ...