import datetime
from typing import Protocol, runtime_checkable


@runtime_checkable
class _IRSwapGenericObject(Protocol):

    def effective_date(self) -> datetime.date: ...
    def maturity_date(self) -> datetime.date: ...

    def fixed_rate(self) -> float: ...
    def set_fixed_rate(self, rate_decimal: float) -> None: ...
    def nominal(self) -> float: ...
    def with_notional(self, notional: float) -> "_IRSwapGenericObject": ...

    def fair_rate(self) -> float: ...
    def npv(self) -> float: ...
    def pv01(self) -> float: ...

    def dv01(self, shift: float = 1e-4) -> float: ...
    def gamma(self, shift: float = 1e-4) -> float: ...

    def dollar_carry(self, horizon: str) -> float: ...
    def carry_bps_running(self, horizon: str) -> float: ...
    def roll_bps_running(self, horizon: str) -> float: ...
    def carry_and_roll_bps_running(self, horizon: str) -> float: ...

