# ABOUTME: Abstract interface for yield curves that price interest rate swaps
# ABOUTME: Defines curve operations (building swaps, computing values, calendar handling) independent of backend
import datetime
from abc import ABC
from typing import Any, Dict, Optional, Protocol, runtime_checkable

from Query.Base._GenericPricable import _GenericPricable
from Query.Base._GenericPricer import _GenericPricer
from Query.IRSwaps._IRSwapGenericObject import _IRSwapGenericObject


class _IRSwapGenericCurve(_GenericPricer[_GenericPricable], ABC):

    def id(self) -> str: ...
    def reference_date(self) -> datetime.date: ...
    def calendar(self) -> Any: ...
    def calendar_advance(self, dt1: datetime.date, dt2: datetime.date) -> datetime.date: ...
    def handle(self) -> Any: ...
    def index(self) -> Any: ...
    def meta(self) -> Any: ...

    def effective_date(self, irswap: _IRSwapGenericObject) -> datetime.date: ...
    def maturity_date(self, irswap: _IRSwapGenericObject) -> datetime.date: ...
    def fixed_rate(self, irswap: _IRSwapGenericObject) -> float: ...
    def set_fixed_rate(self, irswap: _IRSwapGenericObject, rate_decimal: float) -> None: ...
    def notional(self, irswap: _IRSwapGenericObject) -> float: ...
    def fair_rate(self, irswap: _IRSwapGenericObject) -> float: ...
    def npv(self, irswap: _IRSwapGenericObject) -> float: ...
    def pv01(self, irswap: _IRSwapGenericObject) -> float: ...
    def dv01(self, irswap: _IRSwapGenericObject, shift: float = 1e-4) -> float: ...
    def gamma(self, irswap: _IRSwapGenericObject, shift: float = 1e-4) -> float: ...
    def dollar_carry(self, irswap: _IRSwapGenericObject, horizon: str) -> float: ...
    def carry_bps_running(self, irswap: _IRSwapGenericObject, horizon: str) -> float: ...
    def roll_bps_running(self, irswap: _IRSwapGenericObject, horizon: str) -> float: ...
    def carry_and_roll_bps_running(self, irswap: _IRSwapGenericObject, horizon: str) -> float: ...

    def nodes(self) -> Dict[datetime.date, float]: ...

    def resolve_pricable(self, irswap: _IRSwapGenericObject, risk_weight: Optional[float] = None) -> _IRSwapGenericObject: ...

    def build_irswap(
        self,
        fwd: Optional[str] = None,
        tenor: Optional[str] = None,
        effective_date: Optional[datetime.date] = None,
        maturity_date: Optional[datetime.date] = None,
        fixed_rate: Optional[float] = -0.00,
        notional: Optional[float] = None,
        bpv: Optional[float] = None,
    ) -> Any: ...

    def build_stirf(
        self,
        fwd: Optional[str] = None,
        tenor: Optional[str] = None,
        effective_date: Optional[datetime.date] = None,
        maturity_date: Optional[datetime.date] = None,
        fixed_rate: Optional[float] = -0.00,
        notional: Optional[float] = None,
        bpv: Optional[float] = None,
        is_ser: Optional[bool] = False,
    ) -> Any: ...
