import datetime
from abc import ABC
from typing import Any, Optional

from Query.Base._GenericPricable import _GenericPricable
from Query.Base._GenericPricer import _GenericPricer


class _FXForwardGenericPricer(_GenericPricer[_GenericPricable], ABC):

    def id(self) -> str: ...
    def pair(self) -> str: ...
    def symbol(self) -> str: ...
    def tenor(self) -> str: ...
    def settlement_date(self) -> datetime.date: ...
    def quote_timestamp(self) -> datetime.datetime: ...

    def spot(self) -> float: ...
    def points_raw(self) -> float: ...
    def points_decimal(self) -> float: ...
    def forward_rate(self) -> float: ...

    def basis_bps(self) -> Optional[float]: ...
    def fx_rates(self) -> Any: ...
    def fx_forwards(self) -> Any: ...
    def meta(self) -> Any: ...
