CURVE_DEFINITIONS = {
    # --- USD ---
    "USD-SOFR-1D": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "USD-SOFR-OIS Compound/USD-SOFR-COMPOUND",
        "NotionalCurrency": "USD",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "DAYS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "ACT/360",
        "Calendar": "US Government Bond",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZXQ4R16245X", "QZPB5VSBGRCD"],
    },
    "USD-FEDFUNDS": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "USD-Federal Funds-H.15-OIS-COMPOUND/USD-Federal Funds-OIS Compound",
        "NotionalCurrency": "USD",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "DAYS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "ACT/360",
        "Calendar": "US Government Bond",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    "USD-OIS": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "USD-Federal Funds-H.15-OIS-COMPOUND/USD-Federal Funds-OIS Compound",
        "NotionalCurrency": "USD",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "DAYS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "ACT/360",
        "Calendar": "US Government Bond",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": ["QZFF9TXNNM7X", "QZ7HZS5V2LQS"],
    },
    # --- CAD ---
    "CAD-CORRA": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "CAD-CORRA-OIS-COMPOUND/CAD-CORRA-COMPOUND",
        "NotionalCurrency": "CAD",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "DAYS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "ACT/365F",
        "Calendar": "Toronto",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    # --- EUR ---
    "EUR-EURIBOR-6M": {
        "UseCase": "Fixed_Float_IBOR",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "EUR-EURIBOR/EUR-EURIBOR-6M",
        "NotionalCurrency": "EUR",
        "ReferenceRateTermValue": 6,
        "ReferenceRateTermUnit": "MONTHS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "30E/360",
        "Calendar": "TARGET",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    "EUR-EURIBOR-1M": {
        "UseCase": "Fixed_Float_IBOR",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "EUR-EURIBOR/EUR-EURIBOR-1M",
        "NotionalCurrency": "EUR",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "MONTHS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "30E/360",
        "Calendar": "TARGET",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    "EUR-EURIBOR-3M": {
        "UseCase": "Fixed_Float_IBOR",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "EUR-EURIBOR/EUR-EURIBOR-3M",
        "NotionalCurrency": "EUR",
        "ReferenceRateTermValue": 3,
        "ReferenceRateTermUnit": "MONTHS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "30E/360",
        "Calendar": "TARGET",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    "EUR-ESTR": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "EUR-ESTR-OIS-COMPOUND/EUR-ESTR",
        "NotionalCurrency": "EUR",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "DAYS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "ACT/360",
        "Calendar": "TARGET",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
    # --- JPY ---
    "JPY-TONAR": {
        "UseCase": "Fixed_Float_OIS",
        "SingleorMultiCurrency": "Single Currency",
        "ReferenceRate": "JPY-TONAR-OIS-COMPOUND/JPY-TONAR",
        "NotionalCurrency": "JPY",
        "ReferenceRateTermValue": 1,
        "ReferenceRateTermUnit": "DAYS",
        "NotionalSchedule": "Constant",
        "DeliveryType": "PHYS",
        "DayCounter": "ACT/365F",
        "Calendar": "Tokyo",
        "BusinessConvention": "Modified Following",
        "Frequency": "Annual",
        "PaymentLag": 2,
        "SettlementDays": 2,
        "SDR_UPIs": [],
    },
}
