import datetime
from abc import ABC
from typing import Any, Dict, Optional, Protocol, runtime_checkable

from Query.Base._GenericPricable import _GenericPricable
from Query.Base._GenericPricer import _GenericPricer

from Query.STIRFutures._STIRFutureGenericPricable import _STIRFutureGenericPricable


class _STIRFutureGenericPricer(_GenericPricer[_GenericPricable], ABC):

    def id(self) -> str: ...
    def reference_date(self) -> datetime.date: ...
    def calendar(self) -> Any: ...
    def calendar_advance(self, dt1: datetime.date, dt2: datetime.date) -> datetime.date: ...
    def handle(self) -> Any: ...
    def index(self) -> Any: ...
    def meta(self) -> Any: ...

    def effective_date(self, stirf: _STIRFutureGenericPricable) -> datetime.date: ...
    def maturity_date(self, stirf: _STIRFutureGenericPricable) -> datetime.date: ...
    def fixed_rate(self, stirf: _STIRFutureGenericPricable) -> float: ...
    def set_fixed_rate(self, stirf: _STIRFutureGenericPricable, rate_decimal: float) -> None: ...
    def notional(self, stirf: _STIRFutureGenericPricable) -> float: ...
    def fair_rate(self, stirf: _STIRFutureGenericPricable) -> float: ...
    def npv(self, stirf: _STIRFutureGenericPricable) -> float: ...
    def pv01(self, stirf: _STIRFutureGenericPricable, contracts=None, notional=None) -> float: ...
    def dv01(self, stirf: _STIRFutureGenericPricable, shift: float = 1e-4) -> float: ...
    def gamma(self, stirf: _STIRFutureGenericPricable, shift: float = 1e-4) -> float: ...
    def dollar_carry(self, stirf: _STIRFutureGenericPricable, horizon: str) -> float: ...
    def carry_bps_running(self, stirf: _STIRFutureGenericPricable, horizon: str) -> float: ...
    def roll_bps_running(self, stirf: _STIRFutureGenericPricable, horizon: str) -> float: ...
    def carry_and_roll_bps_running(self, stirf: _STIRFutureGenericPricable, horizon: str) -> float: ...

    def resolve_pricable(self, stirf: _STIRFutureGenericPricable, risk_weight: Optional[float] = None) -> _STIRFutureGenericPricable: ...

    def build_stirf(
        self,
        fwd: Optional[str] = None,
        tenor: Optional[str] = None,
        effective_date: Optional[datetime.date] = None,
        maturity_date: Optional[datetime.date] = None,
        fixed_rate: Optional[float] = -0.00,
        notional: Optional[float] = None,
        bpv: Optional[float] = None,
        is_ser: Optional[bool] = False,
    ) -> Any: ...
