r"""Every Citi Velocity ``RATES.*`` tag the committed catalog can name, as enums.

GENERATED by ``scripts/gen_citivelo_tag_enums.py``. DO NOT EDIT BY HAND - see
:mod:`Query.CitiVelocity.tag_enums._base` for the design, the measured provenance
of the tag universe, and what this enum deliberately does not cover.

67,425 tags across 33 families. Two equivalent entry points::

    from Query.CitiVelocity import CitiVeloQuery
    CitiVeloQuery(tag=CitiVeloQuery.Tags.OIS.USD_SOFR.PAR_10Y)

    from Query.CitiVelocity.tag_enums import OIS
    CitiVeloQuery(tag=OIS.USD_SOFR.PAR_10Y)

Nothing is imported until it is touched
---------------------------------------
Constructing all 67,425 enum members costs about 1.6 s and most callers want
one family. So the family modules are loaded on first attribute access, through
PEP 562 ``__getattr__`` here and a metaclass ``__getattr__`` on :class:`CitiVeloTags`.
The ``TYPE_CHECKING`` block below is what keeps that invisible to a language
server: the names are declared statically for completion, and never imported at
run time unless asked for.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any, List, Tuple

from Query.CitiVelocity.tag_enums._base import (
    DEPRECATED_VOL_BRANCHES,
    MAX_FLAT_MEMBERS,
    TAG_PREFIX,
    CitiVeloTag,
    TagNamespace,
    family_of,
    mangle,
)
from Query.CitiVelocity.tag_enums._manifest import (
    CATALOG_FINGERPRINT,
    COUNTS,
    FAMILIES,
    GENERATED_FROM,
    TOTAL,
)

if TYPE_CHECKING:  # pragma: no cover - completion only, never imported at run time
    from Query.CitiVelocity.tag_enums.agency_inventory import AGENCY_INVENTORY as AGENCY_INVENTORY
    from Query.CitiVelocity.tag_enums.basis_swaps import BASIS_SWAPS as BASIS_SWAPS
    from Query.CitiVelocity.tag_enums.bench_rates import BENCH_RATES as BENCH_RATES
    from Query.CitiVelocity.tag_enums.bond import BOND as BOND
    from Query.CitiVelocity.tag_enums.flows import FLOWS as FLOWS
    from Query.CitiVelocity.tag_enums.forecast import FORECAST as FORECAST
    from Query.CitiVelocity.tag_enums.fra import FRA as FRA
    from Query.CitiVelocity.tag_enums.fra_ois import FRA_OIS as FRA_OIS
    from Query.CitiVelocity.tag_enums.futures import FUTURES as FUTURES
    from Query.CitiVelocity.tag_enums.inflation import INFLATION as INFLATION
    from Query.CitiVelocity.tag_enums.invoicespread import INVOICESPREAD as INVOICESPREAD
    from Query.CitiVelocity.tag_enums.liquidity_idx import LIQUIDITY_IDX as LIQUIDITY_IDX
    from Query.CitiVelocity.tag_enums.mbs import MBS as MBS
    from Query.CitiVelocity.tag_enums.midcurves import MIDCURVES as MIDCURVES
    from Query.CitiVelocity.tag_enums.money_markets import MONEY_MARKETS as MONEY_MARKETS
    from Query.CitiVelocity.tag_enums.ois import OIS as OIS
    from Query.CitiVelocity.tag_enums.ois_invoicespread import OIS_INVOICESPREAD as OIS_INVOICESPREAD
    from Query.CitiVelocity.tag_enums.ois_meeting import OIS_MEETING as OIS_MEETING
    from Query.CitiVelocity.tag_enums.pos_mon import POS_MON as POS_MON
    from Query.CitiVelocity.tag_enums.repo import REPO as REPO
    from Query.CitiVelocity.tag_enums.sov import SOV as SOV
    from Query.CitiVelocity.tag_enums.spread_options import SPREAD_OPTIONS as SPREAD_OPTIONS
    from Query.CitiVelocity.tag_enums.ssa import SSA as SSA
    from Query.CitiVelocity.tag_enums.ssa_cs import SSA_CS as SSA_CS
    from Query.CitiVelocity.tag_enums.swap_internal import SWAP_INTERNAL as SWAP_INTERNAL
    from Query.CitiVelocity.tag_enums.swap_libor import SWAP_LIBOR as SWAP_LIBOR
    from Query.CitiVelocity.tag_enums.tsy import TSY as TSY
    from Query.CitiVelocity.tag_enums.vol import VOL as VOL
    from Query.CitiVelocity.tag_enums.xccy_basis_internal import XCCY_BASIS_INTERNAL as XCCY_BASIS_INTERNAL
    from Query.CitiVelocity.tag_enums.xccy_ois_swap import XCCY_OIS_SWAP as XCCY_OIS_SWAP
    from Query.CitiVelocity.tag_enums.xccy_ois_swap_iuo import XCCY_OIS_SWAP_IUO as XCCY_OIS_SWAP_IUO
    from Query.CitiVelocity.tag_enums.xccy_swap import XCCY_SWAP as XCCY_SWAP
    from Query.CitiVelocity.tag_enums.xccy_swap_iuo import XCCY_SWAP_IUO as XCCY_SWAP_IUO


_MODULES = {
    "AGENCY_INVENTORY": "agency_inventory",
    "BASIS_SWAPS": "basis_swaps",
    "BENCH_RATES": "bench_rates",
    "BOND": "bond",
    "FLOWS": "flows",
    "FORECAST": "forecast",
    "FRA": "fra",
    "FRA_OIS": "fra_ois",
    "FUTURES": "futures",
    "INFLATION": "inflation",
    "INVOICESPREAD": "invoicespread",
    "LIQUIDITY_IDX": "liquidity_idx",
    "MBS": "mbs",
    "MIDCURVES": "midcurves",
    "MONEY_MARKETS": "money_markets",
    "OIS": "ois",
    "OIS_INVOICESPREAD": "ois_invoicespread",
    "OIS_MEETING": "ois_meeting",
    "POS_MON": "pos_mon",
    "REPO": "repo",
    "SOV": "sov",
    "SPREAD_OPTIONS": "spread_options",
    "SSA": "ssa",
    "SSA_CS": "ssa_cs",
    "SWAP_INTERNAL": "swap_internal",
    "SWAP_LIBOR": "swap_libor",
    "TSY": "tsy",
    "VOL": "vol",
    "XCCY_BASIS_INTERNAL": "xccy_basis_internal",
    "XCCY_OIS_SWAP": "xccy_ois_swap",
    "XCCY_OIS_SWAP_IUO": "xccy_ois_swap_iuo",
    "XCCY_SWAP": "xccy_swap",
    "XCCY_SWAP_IUO": "xccy_swap_iuo",
}


def _load(family: str) -> Any:
    """Import one family module and return its root node."""
    module = importlib.import_module(f"{__name__}.{_MODULES[family]}")
    return getattr(module, family)


def __getattr__(name: str) -> Any:
    """PEP 562 lazy attribute access for the 33 family roots."""
    if name in _MODULES:
        value = _load(name)
        globals()[name] = value  # cache: this module's __getattr__ runs once per family
        return value
    raise AttributeError(
        f"module {__name__!r} has no attribute {name!r}. Families: {', '.join(FAMILIES)}."
    )


def __dir__() -> List[str]:
    return sorted(set(globals()) | set(_MODULES) | set(__all__))


class _TagsMeta(type):
    """Gives :class:`CitiVeloTags` the same lazy attribute access as the module."""

    def __getattr__(cls, name: str) -> Any:
        if name in _MODULES:
            value = _load(name)
            setattr(cls, name, value)
            return value
        raise AttributeError(
            f"{cls.__name__} has no family {name!r}. Families: {', '.join(FAMILIES)}."
        )

    def __dir__(cls) -> List[str]:
        return sorted(set(type.__dir__(cls)) | set(_MODULES))

    def __iter__(cls):
        for family in FAMILIES:
            yield _load(family)

    def __len__(cls) -> int:
        return len(FAMILIES)


class CitiVeloTags(metaclass=_TagsMeta):
    """The whole tag tree, one attribute per ``RATES.*`` family.

    Re-exported as :attr:`Query.CitiVelocity.CitiVeloQuery.CitiVeloQuery.Tags`, so
    the enum is reachable from the query class a caller already imported::

        >>> from Query.CitiVelocity import CitiVeloQuery            # doctest: +SKIP
        >>> CitiVeloQuery(tag=CitiVeloQuery.Tags.OIS.USD_SOFR.PAR_10Y)   # doctest: +SKIP

    Every family attribute is either a :class:`TagNamespace` or a
    :class:`CitiVeloTag` enum, and both answer ``node()``, ``children()``,
    ``tags()``, ``search()`` and ``find()`` - so walking the tree never has to
    branch on which one it found.
    """

    if TYPE_CHECKING:  # pragma: no cover - completion only
        AGENCY_INVENTORY: type[AGENCY_INVENTORY]
        BASIS_SWAPS: type[BASIS_SWAPS]
        BENCH_RATES: type[BENCH_RATES]
        BOND: type[BOND]
        FLOWS: type[FLOWS]
        FORECAST: type[FORECAST]
        FRA: type[FRA]
        FRA_OIS: type[FRA_OIS]
        FUTURES: type[FUTURES]
        INFLATION: type[INFLATION]
        INVOICESPREAD: type[INVOICESPREAD]
        LIQUIDITY_IDX: type[LIQUIDITY_IDX]
        MBS: type[MBS]
        MIDCURVES: type[MIDCURVES]
        MONEY_MARKETS: type[MONEY_MARKETS]
        OIS: type[OIS]
        OIS_INVOICESPREAD: type[OIS_INVOICESPREAD]
        OIS_MEETING: type[OIS_MEETING]
        POS_MON: type[POS_MON]
        REPO: type[REPO]
        SOV: type[SOV]
        SPREAD_OPTIONS: type[SPREAD_OPTIONS]
        SSA: type[SSA]
        SSA_CS: type[SSA_CS]
        SWAP_INTERNAL: type[SWAP_INTERNAL]
        SWAP_LIBOR: type[SWAP_LIBOR]
        TSY: type[TSY]
        VOL: type[VOL]
        XCCY_BASIS_INTERNAL: type[XCCY_BASIS_INTERNAL]
        XCCY_OIS_SWAP: type[XCCY_OIS_SWAP]
        XCCY_OIS_SWAP_IUO: type[XCCY_OIS_SWAP_IUO]
        XCCY_SWAP: type[XCCY_SWAP]
        XCCY_SWAP_IUO: type[XCCY_SWAP_IUO]

    #: SHA-256 of the catalog artefacts these tags were generated from.
    FINGERPRINT = CATALOG_FINGERPRINT
    #: ``{family: tag count}``.
    COUNTS = COUNTS
    #: Every family name, in catalog order.
    FAMILIES = FAMILIES
    #: Total tags across every family.
    TOTAL = TOTAL

    def __init__(self) -> None:  # pragma: no cover - defensive
        raise TypeError("CitiVeloTags is a namespace, not a value. Reach through it: CitiVeloTags.OIS")

    # -- whole-tree helpers -------------------------------------------

    @staticmethod
    def family(name: str) -> Any:
        """The root node of one family, by name.

        >>> CitiVeloTags.family("OIS").node()        # doctest: +SKIP
        'RATES.OIS'
        """
        key = str(name).upper()
        if key.startswith(TAG_PREFIX):
            key = family_of(key)
        if key not in _MODULES:
            raise KeyError(f"{name!r} is not a Citi Velocity family. Families: {', '.join(FAMILIES)}.")
        return _load(key)

    @staticmethod
    def find(tag: str) -> CitiVeloTag:
        """Resolve any tag string to its member, loading only that family.

        The inverse of the one-way name mangling, and the reason the tree's
        variable depth never blocks anyone: you do not need to know how deep a tag
        sits, or how its name was spelled, to get the typed member back.

        >>> CitiVeloTags.find("RATES.OIS.USD_SOFR.PAR.10Y")      # doctest: +SKIP
        <PAR_10Y: 'RATES.OIS.USD_SOFR.PAR.10Y'>
        """
        return CitiVeloTags.family(family_of(str(tag))).find(str(tag))

    @staticmethod
    def search(pattern: str, *, family: str = "", limit: int = 200) -> List[CitiVeloTag]:
        """Members matching a glob, a ``/regex/`` or a substring.

        Scope it with ``family=`` when you can. Unscoped, this loads **every**
        family, which is the one operation in this package that is not cheap; the
        cost is stated rather than hidden because a search in a loop would
        otherwise look free.
        """
        if family:
            return CitiVeloTags.family(family).search(pattern, limit=limit)
        out: List[CitiVeloTag] = []
        for name in FAMILIES:
            out.extend(_load(name).search(pattern, limit=limit))
            if len(out) >= limit:
                break
        return out[:limit]

    @staticmethod
    def counts() -> Tuple[Tuple[str, int], ...]:
        """``(family, tag count)`` biggest first, without importing anything."""
        return tuple(sorted(COUNTS.items(), key=lambda kv: (-kv[1], kv[0])))


__all__ = [
    "CitiVeloTag",
    "CitiVeloTags",
    "TagNamespace",
    "CATALOG_FINGERPRINT",
    "COUNTS",
    "DEPRECATED_VOL_BRANCHES",
    "FAMILIES",
    "GENERATED_FROM",
    "MAX_FLAT_MEMBERS",
    "TAG_PREFIX",
    "TOTAL",
    "family_of",
    "mangle",
] + list(_MODULES)
