r"""The two hand-written types every generated Citi Velocity tag module is built from.

The 33 family modules beside this one are generated by
``scripts/gen_citivelo_tag_enums.py``. This file is not, and is where the reasoning
lives.

Why ``StrEnum`` and not ``(str, Enum)``
--------------------------------------
Everything downstream of a tag treats it as a string: the pricer does
``classify_tag(str(explicit))``, the tag cache builds a parquet filename from it,
and pandas uses it as a column label. Under a plain ``(str, Enum)`` mixin,
``str(member)`` returns ``"OIS.USD_SOFR_PAR_10Y"`` on some Python versions and
``"RATES.OIS.USD_SOFR.PAR.10Y"`` on others - the 3.11 enum change moved it - so a
member that works on one interpreter silently produces a *bad tag* on another.
:class:`enum.StrEnum` pins ``__str__`` to ``str.__str__``, which makes
"``str(member)`` is the tag" a property of the type rather than of the
interpreter. ``tests/test_citivelo_tag_enums.py`` asserts it in five formatting
contexts anyway, because a convention that is only documented is not a guarantee.

Where the tags come from, measured
----------------------------------
The universe is :meth:`~MDP.CitiVelocityExcel.catalog.CitiVeloCatalog.expand` over
all 33 families - the catalog's own path-consistent generation rule - and **not**
the flat ``leaves`` list in ``rates_catalog.json``. That choice was measured, not
assumed:

===============================  ==========  ==========  ================
family                           flat list   expand()    overlap
===============================  ==========  ==========  ================
27 of the 33 families            identical   identical   100%
``VOL``                          263         26,233      **0**
``INFLATION``                    293         6,864       5
``REPO``                         16          224         **0**
``XCCY_OIS_SWAP``                1,960       10,980      1,740
``MONEY_MARKETS``                150         192         147
===============================  ==========  ==========  ================

The flat list's entries for those families are **truncated internal nodes, not
tags**: ``RATES.VOL.AUD.ATM.BLACK`` still needs an expiry and a tenor before
``CVTSHIST`` will look at it. And the one live probe of generated tags
(``shape3_results.json``: 1,546 tags through ``CVTSHIST``, 1,456 shape-correct)
sampled exactly the three deep families where the two disagree, and every one of
its 1,456 confirmed tags is inside ``expand()``. So the deeper artefact is both
the more complete one and the only one with live evidence behind it.

What this enum does NOT claim
-----------------------------
That every member serves data. 94% is the measured shape-correct rate on the
one probe that exists, and it covered 3 of 33 families - the other 30 have never
been probed at all. Members carry :meth:`CitiVeloTag.verification`, which is
``unverified`` for the overwhelming majority, and ``unverified`` is an honest
answer rather than a failure. Two further boundaries:

* The four legacy ``VOL`` branches (``ATM``, ``OTM``, ``REALIZED``,
  ``VOL_RATIO``) are **kept**, because they are real recorded structure and 46 of
  the probe's confirmed tags sit under them - but they are known to return no
  data, so :attr:`CitiVeloTag.deprecated` flags them and the ``_RFR`` twins are
  what a caller wants. They land in their own namespace nodes, so intellisense
  separates them without anyone having to remember this.
* Bond tags key off an ISIN universe that turns over weekly (auctions, maturities).
  Freezing it into committed source guarantees a stale answer, so bonds stay with
  ``MDP.CitiVelocityExcel.tags.bond(isin, measure)`` over the live
  ``CVCURVEBOND`` universe.

Any ``RATES.*`` string is still accepted everywhere a member is. This is a
discovery surface, not a gate: "the enum did not have it" must never read as
"Citi does not serve it".

This reverses a stated design, deliberately
-------------------------------------------
:mod:`MDP.CitiVelocityExcel.catalog` opens with "The catalog is a **grammar, not
a tag list.** Walking the Function Builder to every leaf was attempted and
abandoned on evidence." That argument is about **harvesting** - about not
spending ~9 hours of UI selections and ``CVTSHIST`` probes to enumerate something
the grammar already describes - and it still stands. Nothing here re-walks
anything: this tree is generated offline from the committed grammar in a second,
and it touches no add-in. What it adds is the thing a grammar cannot give you,
which is a name you can find by typing a dot. The grammar remains the source of
truth; :meth:`~MDP.CitiVelocityExcel.catalog.CitiVeloCatalog.expand` remains the
generator; this is its rendering.

The trap the enum makes easier to reach
---------------------------------------
Roughly half of these tags classify as ``RAW``: the pricer has no model for them,
so they carry ``CitiVeloUnit.RATIO`` and a ``scale_to_bp`` of 1.0. The structure
layer's ``_assert_same_unit`` guard cannot see inside ``RAW``, so a ``SPREAD``
built from, say, a ``REPO`` leg and an ``SSA`` leg nets two unrelated families and
returns a number without complaint. With raw strings that combination was hard to
type by accident; with completion it is two keystrokes. :attr:`CitiVeloTag.is_repriceable`
and :meth:`CitiVeloTag.kind` are here so the surface can tell you before the
trade does.

Why the tree has variable depth
-------------------------------
A single flat enum per family puts 26,233 members in one ``VOL`` class and one
~2 MB source file, which is a completion list nobody can read and a file the
language server indexes slowly. So a node becomes a flat enum once it holds
:data:`MAX_FLAT_MEMBERS` tags or fewer, and otherwise splits on its next segment
and recurses. Measured over the 67,425-tag universe that gives 468 classes with a
mean of 144 members and a worst case of 2,040 - a completion list you can
actually scan.

The cost is that depth is not uniform: ``TSY`` is a flat enum at the family level
while ``VOL.USD.OTM_RFR.NORMALABSOLUTE`` is four levels down. That is paid for by
giving :class:`TagNamespace` and :class:`CitiVeloTag` the **same** protocol -
``tags()``, ``search()``, ``find()``, ``children()``, iteration - so no caller
ever has to know which one it is holding, and by :func:`~.find` at the package
root, which resolves any tag string to its member no matter how deep it sits.
"""

from __future__ import annotations

import enum
import fnmatch
import re
from typing import Any, Dict, Iterator, List, Optional, Tuple, Union

__all__ = [
    "CitiVeloTag",
    "TagNamespace",
    "TAG_PREFIX",
    "MAX_FLAT_MEMBERS",
    "DEPRECATED_VOL_BRANCHES",
    "mangle",
    "family_of",
]

#: Every tag the add-in accepts starts here. Asserted at generation time.
TAG_PREFIX = "RATES."

#: The generator splits a node rather than emitting a flat enum above this size.
#: Recorded here rather than only in the generator so a reader of the generated
#: code can see why a family is shaped the way it is.
MAX_FLAT_MEMBERS = 1024

#: Recorded, reachable, and known to return no data - see the module docstring.
#: Duplicated from :data:`MDP.CitiVelocityExcel.catalog.DEPRECATED_VOL_BRANCHES`
#: rather than imported, so this package pulls in no ``MDP`` module at import
#: time; ``tests/test_citivelo_tag_enums.py`` asserts the two stay equal.
DEPRECATED_VOL_BRANCHES: Tuple[str, ...] = ("ATM", "OTM", "REALIZED", "VOL_RATIO")

#: ``1D 1W 2W 1M ... 40Y`` and the odd ``21M``/``15M``. Mirrors
#: :data:`MDP.CitiVelocityExcel.catalog.TENOR_RE`, duplicated for the same reason.
_TENOR_RE = re.compile(r"^\d+[DWMY]$")


def family_of(tag: str) -> str:
    """The family segment of a tag, without the ``RATES.`` prefix.

    >>> family_of("RATES.OIS.USD_SOFR.PAR.10Y")
    'OIS'
    """
    text = str(tag)
    if not text.startswith(TAG_PREFIX):
        raise ValueError(f"Not a Citi Velocity tag (must start with {TAG_PREFIX!r}): {tag!r}")
    return text[len(TAG_PREFIX) :].split(".", 1)[0]


def mangle(segment_path: str) -> str:
    """The Python identifier one or more dotted segments become.

    Dots become underscores; a name that would start with a digit gets an ``N``
    prefix, because ``3S1S_BASIS`` is not a Python identifier. The mapping is
    one-way, so the generator checks it is injective within every node and
    **raises** rather than letting the second of two colliding tags silently win.

    >>> mangle("PAR.10Y")
    'PAR_10Y'
    >>> mangle("3S1S_BASIS")
    'N3S1S_BASIS'
    """
    name = str(segment_path).replace(".", "_")
    if not name:
        return "ROOT"
    if name[0].isdigit():
        name = "N" + name
    return name


def _search_values(
    values: List[str], pattern: str, *, limit: int
) -> List[str]:
    """Glob / ``/regex/`` / case-insensitive substring, the catalog's own dispatch.

    Kept identical to
    :meth:`MDP.CitiVelocityExcel.catalog.CitiVeloCatalog.search` so a reader who
    knows one knows the other.
    """
    text = str(pattern)
    if text.startswith("/") and text.endswith("/") and len(text) > 2:
        rx = re.compile(text[1:-1], re.IGNORECASE)
        hits = [v for v in values if rx.search(v)]
    elif any(ch in text for ch in "*?["):
        hits = [v for v in values if fnmatch.fnmatch(v, text)]
    else:
        needle = text.upper()
        hits = [v for v in values if needle in v.upper()]
    return hits[: int(limit)]


def _is_deprecated(tag: str) -> bool:
    parts = str(tag).split(".")
    return len(parts) > 3 and parts[1] == "VOL" and parts[3] in DEPRECATED_VOL_BRANCHES


class CitiVeloTag(enum.StrEnum):
    """A published Citi Velocity ``RATES.*`` tag.

    Generated subclasses hold the members. A member *is* a ``str``, so it goes
    anywhere a tag string goes::

        >>> from Query.CitiVelocity.tag_enums import OIS          # doctest: +SKIP
        >>> OIS.USD_SOFR.PAR_10Y                                  # doctest: +SKIP
        <PAR_10Y: 'RATES.OIS.USD_SOFR.PAR.10Y'>
        >>> str(OIS.USD_SOFR.PAR_10Y)                             # doctest: +SKIP
        'RATES.OIS.USD_SOFR.PAR.10Y'
    """

    # -- what one tag is --------------------------------------------------

    @property
    def family(self) -> str:
        """``OIS``, ``VOL``, ``SWAP_LIBOR``, ... - the segment after ``RATES.``."""
        return family_of(self.value)

    @property
    def segments(self) -> Tuple[str, ...]:
        """The dotted segments below ``RATES.<FAMILY>``.

        >>> from Query.CitiVelocity.tag_enums import OIS          # doctest: +SKIP
        >>> OIS.USD_SOFR.PAR_10Y.segments                         # doctest: +SKIP
        ('USD_SOFR', 'PAR', '10Y')
        """
        head = f"{TAG_PREFIX}{self.family}"
        rest = self.value[len(head) :].lstrip(".")
        return tuple(rest.split(".")) if rest else tuple()

    @property
    def tenor(self) -> Optional[str]:
        """The trailing segment when it looks like a tenor, else ``None``.

        Deliberately shallow - it reads the last segment and nothing else. A
        family whose tenor is not last (``XCCY_OIS_SWAP`` ends on the leg token)
        gets ``None`` rather than a plausible wrong answer.
        """
        segs = self.segments
        return segs[-1] if segs and _TENOR_RE.match(segs[-1]) else None

    @property
    def deprecated(self) -> bool:
        """True for the four legacy ``VOL`` branches, which serve no data.

        See the module docstring: they are kept because they are real recorded
        structure, and flagged because reaching for ``ATM`` when you meant
        ``ATM_RFR`` produces an empty series rather than an error.
        """
        return _is_deprecated(self.value)

    def verification(self) -> str:
        """``valid`` | ``empty`` | ``shape_ok`` | ``failed`` | ``unverified``.

        **Probe residue, not a gate.** Measured over this universe it is close to
        vacuous: essentially every member comes back ``unverified``, because the
        catalog records structure for far more tags than were ever put through
        ``CVTSHIST``. Worse, a ``valid`` verdict has two unrelated provenances -
        a shape probe, or the separate bond sweep, which
        :meth:`~MDP.CitiVelocityExcel.catalog.CitiVeloCatalog.verification` also
        answers ``valid`` for. Filtering on it keeps almost everything and proves
        almost nothing. The real check is
        :meth:`~MDP.CitiVelocityExcel.com_client.CitiVelocityExcelClient.validate_with_controls`,
        which goes through ``CVTSHIST`` and refuses to report at all if its own
        control tags fail.

        Delegates to the catalog, imported inside the call rather than at module
        scope for two reasons: it keeps the ``Query`` layer free of an ``MDP``
        import for the common case of simply naming a tag, and the catalog's JSON
        artefacts are ~1.6 MB a caller who only wanted a string should not load.
        """
        from MDP.CitiVelocityExcel.catalog import CitiVeloCatalog

        return CitiVeloCatalog.default().verification(self.value)

    def kind(self) -> Any:
        """The :class:`~Query.CitiVelocity._CitiVeloLeg.CitiVeloKind` this tag resolves to.

        ``RAW`` is the honest answer for most of this universe and is the one to
        pay attention to - see :attr:`is_repriceable` and the module docstring's
        warning about netting two RAW families.

        Lazily imported like :meth:`verification`, and more expensively: the
        classifier lives in the pricer module, which pulls in the curve builders.
        """
        from MDP.CitiVelocityExcel.pricer import classify_tag

        kind, _fields = classify_tag(self.value)
        return kind

    @property
    def is_repriceable(self) -> bool:
        """True when a locally-built model can reproduce this tag from quotes.

        False means the published quote is the only path: ``QUOTE`` works, and any
        ``RL_*``/``QL_*`` value on this leg will raise rather than approximate.
        Worth checking before building a structure, because the alternative is
        finding out at pricing time.
        """
        return bool(getattr(self.kind(), "repriceable", False))

    # -- the shared protocol ----------------------------------------------

    @classmethod
    def node(cls) -> str:
        """The dotted catalog node this enum sits at."""
        return getattr(cls, "__node__", TAG_PREFIX.rstrip("."))

    @classmethod
    def children(cls) -> Tuple[str, ...]:
        """Attribute names one level down. For an enum, its member names."""
        return tuple(m.name for m in cls)

    @classmethod
    def tags(cls) -> Tuple[str, ...]:
        """Every tag at or below here, in catalog order."""
        return tuple(m.value for m in cls)

    @classmethod
    def search(cls, pattern: str, *, limit: int = 200) -> List["CitiVeloTag"]:
        """Members matching a glob (``*USD_SOFR*PAR*``), a ``/regex/`` or a substring."""
        by_value = {m.value: m for m in cls}
        return [by_value[v] for v in _search_values(list(by_value), pattern, limit=limit)]

    @classmethod
    def find(cls, tag: str) -> "CitiVeloTag":
        """The member for an exact tag string, or ``KeyError`` naming near misses.

        The inverse of the one-way name mangling: a caller holding a tag out of a
        log, a config file or someone else's notebook gets the typed member back
        without having to guess how its name was spelled.

        The miss message always carries examples. A near-miss search on the
        trailing segment finds nothing at all when that segment is the wrong part
        (``...PAR.99Y`` - there is no ``99Y`` anywhere), and "not found" with no
        suggestion is the least useful thing this could say, so it falls back to
        showing what this node *does* hold.
        """
        text = str(tag)
        try:
            return cls(text)
        except ValueError:
            pass
        near = [m.value for m in cls.search(text.rsplit(".", 1)[-1], limit=5)]
        if near:
            hint = f" Closest recorded: {', '.join(near)}."
        else:
            hint = f" Recorded here: {', '.join(m.value for m in list(cls)[:5])}."
        raise KeyError(f"{text!r} is not a recorded tag under {cls.node()!r}.{hint}")

    # -- display ------------------------------------------------------------

    def __repr__(self) -> str:  # pragma: no cover - display only
        return f"<{self.name}: {self.value!r}>"


class TagNamespace:
    """An interior node of the tag tree: a class whose attributes are more nodes.

    Exposes exactly the same four classmethods as :class:`CitiVeloTag` -
    :meth:`node`, :meth:`children`, :meth:`tags`, :meth:`search`, :meth:`find` -
    so a caller walking the tree never has to branch on which kind of node it is
    holding. That symmetry is the whole reason the variable-depth split is
    tolerable; see the module docstring.

    Never instantiated. It is a namespace, and instantiating one would suggest it
    carried state.
    """

    #: Set by the generator on every node. The dotted catalog path.
    __node__: str = TAG_PREFIX.rstrip(".")

    def __init__(self) -> None:  # pragma: no cover - defensive
        raise TypeError(
            f"{type(self).__name__} is a tag namespace, not a value. Reach through it to a "
            f"member (e.g. {type(self).__name__}.<TAB>), or call .tags() for the strings."
        )

    # -- the shared protocol ----------------------------------------------

    @classmethod
    def node(cls) -> str:
        """The dotted catalog node this namespace sits at."""
        return cls.__node__

    @classmethod
    def _child_nodes(cls) -> List[Tuple[str, Any]]:
        """``(attribute name, node)`` for every child, in declaration order.

        Reads ``cls.__dict__`` rather than ``dir()``: ``dir()`` sorts
        alphabetically and would lose the catalog ordering the generator emits,
        and it would also pull in inherited helpers.
        """
        out: List[Tuple[str, Any]] = []
        for name, value in vars(cls).items():
            if name.startswith("_"):
                continue
            if isinstance(value, type) and (
                issubclass(value, TagNamespace) or issubclass(value, CitiVeloTag)
            ):
                out.append((name, value))
        return out

    @classmethod
    def children(cls) -> Tuple[str, ...]:
        """Attribute names one level down."""
        return tuple(name for name, _ in cls._child_nodes())

    @classmethod
    def walk(cls) -> Iterator[Union["CitiVeloTag", Any]]:
        """Every leaf enum class at or below here, depth first."""
        for _, child in cls._child_nodes():
            if isinstance(child, type) and issubclass(child, CitiVeloTag):
                yield child
            else:
                yield from child.walk()

    @classmethod
    def tags(cls) -> Tuple[str, ...]:
        """Every tag at or below here, in catalog order."""
        out: List[str] = []
        for leaf in cls.walk():
            out.extend(m.value for m in leaf)
        return tuple(out)

    @classmethod
    def members(cls) -> Tuple[CitiVeloTag, ...]:
        """Every member at or below here, in catalog order."""
        out: List[CitiVeloTag] = []
        for leaf in cls.walk():
            out.extend(list(leaf))
        return tuple(out)

    @classmethod
    def search(cls, pattern: str, *, limit: int = 200) -> List[CitiVeloTag]:
        """Members at or below here matching a glob, a ``/regex/`` or a substring."""
        by_value: Dict[str, CitiVeloTag] = {m.value: m for m in cls.members()}
        return [by_value[v] for v in _search_values(list(by_value), pattern, limit=limit)]

    @classmethod
    def find(cls, tag: str) -> CitiVeloTag:
        """The member for an exact tag string at or below here.

        Walks only the branch the tag's own segments point at, so resolving one
        tag does not materialise the rest of the family.
        """
        text = str(tag)
        head = cls.__node__
        if text != head and not text.startswith(head + "."):
            raise KeyError(f"{text!r} is not under {head!r}.")
        for _, child in cls._child_nodes():
            child_node = child.node()
            if text == child_node or text.startswith(child_node + "."):
                return child.find(text)  # type: ignore[no-any-return]
        # No child claims this path, so the tag went wrong AT THIS LEVEL. Name the
        # children rather than searching below them: the search would materialise
        # every member under this node (26,233 of them under ``RATES.VOL``) to
        # produce a worse answer than "here are the branches that exist".
        raise KeyError(
            f"{text!r} is not a recorded tag under {head!r}. "
            f"Branches here: {', '.join(cls.children())}."
        )

    def __class_getitem__(cls, item: str) -> Any:  # pragma: no cover - convenience
        """``VOL["USD"]`` for a segment name that is not a Python identifier."""
        return getattr(cls, mangle(item))
