# fmt: off
# ruff: noqa: E501
# flake8: noqa
r"""OIS_INVOICESPREAD tags, generated from the Citi Velocity catalog. DO NOT EDIT BY HAND.

Regenerate with::

    python scripts/gen_citivelo_tag_enums.py

44 tags under ``RATES.OIS_INVOICESPREAD``, arranged as one flat enum.

Edits to this file are lost on the next regeneration, and
``tests/test_citivelo_tag_enums.py`` fails the moment it disagrees with the
catalog - so there is no window in which a hand edit merely looks like it worked.
"""

from __future__ import annotations

from Query.CitiVelocity.tag_enums._base import CitiVeloTag, TagNamespace

__all__ = ["OIS_INVOICESPREAD"]

class OIS_INVOICESPREAD(CitiVeloTag):
    """44 tags under ``RATES.OIS_INVOICESPREAD``."""

    __node__ = "RATES.OIS_INVOICESPREAD"

    EUR_FBON_BACKMONTH_FBON = "RATES.OIS_INVOICESPREAD.EUR_FBON_BACKMONTH.FBON"
    EUR_FBON_FRONTMONTH_FBON = "RATES.OIS_INVOICESPREAD.EUR_FBON_FRONTMONTH.FBON"
    EUR_FBTM_BACKMONTH_FBTM = "RATES.OIS_INVOICESPREAD.EUR_FBTM_BACKMONTH.FBTM"
    EUR_FBTM_FRONTMONTH_FBTM = "RATES.OIS_INVOICESPREAD.EUR_FBTM_FRONTMONTH.FBTM"
    EUR_FBTP_BACKMONTH_FBTP = "RATES.OIS_INVOICESPREAD.EUR_FBTP_BACKMONTH.FBTP"
    EUR_FBTP_FRONTMONTH_FBTP = "RATES.OIS_INVOICESPREAD.EUR_FBTP_FRONTMONTH.FBTP"
    EUR_FBTS_BACKMONTH_FBTS = "RATES.OIS_INVOICESPREAD.EUR_FBTS_BACKMONTH.FBTS"
    EUR_FBTS_FRONTMONTH_FBTS = "RATES.OIS_INVOICESPREAD.EUR_FBTS_FRONTMONTH.FBTS"
    EUR_FGBL_BACKMONTH_FGBL = "RATES.OIS_INVOICESPREAD.EUR_FGBL_BACKMONTH.FGBL"
    EUR_FGBL_FRONTMONTH_FGBL = "RATES.OIS_INVOICESPREAD.EUR_FGBL_FRONTMONTH.FGBL"
    EUR_FGBM_BACKMONTH_FGBM = "RATES.OIS_INVOICESPREAD.EUR_FGBM_BACKMONTH.FGBM"
    EUR_FGBM_FRONTMONTH_FGBM = "RATES.OIS_INVOICESPREAD.EUR_FGBM_FRONTMONTH.FGBM"
    EUR_FGBS_BACKMONTH_FGBS = "RATES.OIS_INVOICESPREAD.EUR_FGBS_BACKMONTH.FGBS"
    EUR_FGBS_FRONTMONTH_FGBS = "RATES.OIS_INVOICESPREAD.EUR_FGBS_FRONTMONTH.FGBS"
    EUR_FGBX_BACKMONTH_FGBX = "RATES.OIS_INVOICESPREAD.EUR_FGBX_BACKMONTH.FGBX"
    EUR_FGBX_FRONTMONTH_FGBX = "RATES.OIS_INVOICESPREAD.EUR_FGBX_FRONTMONTH.FGBX"
    EUR_FOAM_BACKMONTH_FOAM = "RATES.OIS_INVOICESPREAD.EUR_FOAM_BACKMONTH.FOAM"
    EUR_FOAM_FRONTMONTH_FOAM = "RATES.OIS_INVOICESPREAD.EUR_FOAM_FRONTMONTH.FOAM"
    EUR_FOAT_BACKMONTH_FOAT = "RATES.OIS_INVOICESPREAD.EUR_FOAT_BACKMONTH.FOAT"
    EUR_FOAT_FRONTMONTH_FOAT = "RATES.OIS_INVOICESPREAD.EUR_FOAT_FRONTMONTH.FOAT"
    USD_FEDFUND_BACKMONTH_10Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_BACKMONTH.10Y"
    USD_FEDFUND_BACKMONTH_2Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_BACKMONTH.2Y"
    USD_FEDFUND_BACKMONTH_3Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_BACKMONTH.3Y"
    USD_FEDFUND_BACKMONTH_5Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_BACKMONTH.5Y"
    USD_FEDFUND_BACKMONTH_ULTRA10Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_BACKMONTH.ULTRA10Y"
    USD_FEDFUND_FRONTMONTH_10Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_FRONTMONTH.10Y"
    USD_FEDFUND_FRONTMONTH_2Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_FRONTMONTH.2Y"
    USD_FEDFUND_FRONTMONTH_3Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_FRONTMONTH.3Y"
    USD_FEDFUND_FRONTMONTH_5Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_FRONTMONTH.5Y"
    USD_FEDFUND_FRONTMONTH_ULTRA10Y = "RATES.OIS_INVOICESPREAD.USD_FEDFUND_FRONTMONTH.ULTRA10Y"
    USD_SOFR_BACKMONTH_10Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_BACKMONTH.10Y"
    USD_SOFR_BACKMONTH_20Y_BOND = "RATES.OIS_INVOICESPREAD.USD_SOFR_BACKMONTH.20Y_BOND"
    USD_SOFR_BACKMONTH_2Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_BACKMONTH.2Y"
    USD_SOFR_BACKMONTH_30Y_BOND = "RATES.OIS_INVOICESPREAD.USD_SOFR_BACKMONTH.30Y_BOND"
    USD_SOFR_BACKMONTH_3Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_BACKMONTH.3Y"
    USD_SOFR_BACKMONTH_5Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_BACKMONTH.5Y"
    USD_SOFR_BACKMONTH_ULTRA10Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_BACKMONTH.ULTRA10Y"
    USD_SOFR_FRONTMONTH_10Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_FRONTMONTH.10Y"
    USD_SOFR_FRONTMONTH_20Y_BOND = "RATES.OIS_INVOICESPREAD.USD_SOFR_FRONTMONTH.20Y_BOND"
    USD_SOFR_FRONTMONTH_2Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_FRONTMONTH.2Y"
    USD_SOFR_FRONTMONTH_30Y_BOND = "RATES.OIS_INVOICESPREAD.USD_SOFR_FRONTMONTH.30Y_BOND"
    USD_SOFR_FRONTMONTH_3Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_FRONTMONTH.3Y"
    USD_SOFR_FRONTMONTH_5Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_FRONTMONTH.5Y"
    USD_SOFR_FRONTMONTH_ULTRA10Y = "RATES.OIS_INVOICESPREAD.USD_SOFR_FRONTMONTH.ULTRA10Y"

