# fmt: off
# ruff: noqa: E501
# flake8: noqa
r"""SSA_CS tags, generated from the Citi Velocity catalog. DO NOT EDIT BY HAND.

Regenerate with::

    python scripts/gen_citivelo_tag_enums.py

100 tags under ``RATES.SSA_CS``, arranged as one flat enum.

Edits to this file are lost on the next regeneration, and
``tests/test_citivelo_tag_enums.py`` fails the moment it disagrees with the
catalog - so there is no window in which a hand edit merely looks like it worked.
"""

from __future__ import annotations

from Query.CitiVelocity.tag_enums._base import CitiVeloTag, TagNamespace

__all__ = ["SSA_CS"]

class SSA_CS(CitiVeloTag):
    """100 tags under ``RATES.SSA_CS``."""

    __node__ = "RATES.SSA_CS"

    AFDB_EUR_USD_2Y = "RATES.SSA_CS.AFDB.EUR_USD.2Y"
    AFDB_EUR_USD_3Y = "RATES.SSA_CS.AFDB.EUR_USD.3Y"
    AFDB_EUR_USD_5Y = "RATES.SSA_CS.AFDB.EUR_USD.5Y"
    AFDB_EUR_USD_7Y = "RATES.SSA_CS.AFDB.EUR_USD.7Y"
    AIIB_EUR_USD_10Y = "RATES.SSA_CS.AIIB.EUR_USD.10Y"
    AIIB_EUR_USD_2Y = "RATES.SSA_CS.AIIB.EUR_USD.2Y"
    AIIB_EUR_USD_3Y = "RATES.SSA_CS.AIIB.EUR_USD.3Y"
    AIIB_EUR_USD_5Y = "RATES.SSA_CS.AIIB.EUR_USD.5Y"
    ASIA_EUR_USD_10Y = "RATES.SSA_CS.ASIA.EUR_USD.10Y"
    ASIA_EUR_USD_2Y = "RATES.SSA_CS.ASIA.EUR_USD.2Y"
    ASIA_EUR_USD_3Y = "RATES.SSA_CS.ASIA.EUR_USD.3Y"
    ASIA_EUR_USD_5Y = "RATES.SSA_CS.ASIA.EUR_USD.5Y"
    ASIA_EUR_USD_7Y = "RATES.SSA_CS.ASIA.EUR_USD.7Y"
    BNG_EUR_USD_10Y = "RATES.SSA_CS.BNG.EUR_USD.10Y"
    BNG_EUR_USD_2Y = "RATES.SSA_CS.BNG.EUR_USD.2Y"
    BNG_EUR_USD_3Y = "RATES.SSA_CS.BNG.EUR_USD.3Y"
    BNG_EUR_USD_5Y = "RATES.SSA_CS.BNG.EUR_USD.5Y"
    BNG_EUR_USD_7Y = "RATES.SSA_CS.BNG.EUR_USD.7Y"
    CADES_EUR_USD_10Y = "RATES.SSA_CS.CADES.EUR_USD.10Y"
    CADES_EUR_USD_2Y = "RATES.SSA_CS.CADES.EUR_USD.2Y"
    CADES_EUR_USD_3Y = "RATES.SSA_CS.CADES.EUR_USD.3Y"
    CADES_EUR_USD_5Y = "RATES.SSA_CS.CADES.EUR_USD.5Y"
    CADES_EUR_USD_7Y = "RATES.SSA_CS.CADES.EUR_USD.7Y"
    EBRD_EUR_USD_10Y = "RATES.SSA_CS.EBRD.EUR_USD.10Y"
    EBRD_EUR_USD_2Y = "RATES.SSA_CS.EBRD.EUR_USD.2Y"
    EBRD_EUR_USD_3Y = "RATES.SSA_CS.EBRD.EUR_USD.3Y"
    EBRD_EUR_USD_5Y = "RATES.SSA_CS.EBRD.EUR_USD.5Y"
    EBRD_EUR_USD_7Y = "RATES.SSA_CS.EBRD.EUR_USD.7Y"
    EDC_EUR_USD_2Y = "RATES.SSA_CS.EDC.EUR_USD.2Y"
    EDC_EUR_USD_3Y = "RATES.SSA_CS.EDC.EUR_USD.3Y"
    EDC_EUR_USD_5Y = "RATES.SSA_CS.EDC.EUR_USD.5Y"
    EIB_EUR_USD_10Y = "RATES.SSA_CS.EIB.EUR_USD.10Y"
    EIB_EUR_USD_2Y = "RATES.SSA_CS.EIB.EUR_USD.2Y"
    EIB_EUR_USD_3Y = "RATES.SSA_CS.EIB.EUR_USD.3Y"
    EIB_EUR_USD_5Y = "RATES.SSA_CS.EIB.EUR_USD.5Y"
    EIB_EUR_USD_7Y = "RATES.SSA_CS.EIB.EUR_USD.7Y"
    IADB_EUR_USD_10Y = "RATES.SSA_CS.IADB.EUR_USD.10Y"
    IADB_EUR_USD_2Y = "RATES.SSA_CS.IADB.EUR_USD.2Y"
    IADB_EUR_USD_3Y = "RATES.SSA_CS.IADB.EUR_USD.3Y"
    IADB_EUR_USD_5Y = "RATES.SSA_CS.IADB.EUR_USD.5Y"
    IADB_EUR_USD_7Y = "RATES.SSA_CS.IADB.EUR_USD.7Y"
    IBRD_EUR_USD_10Y = "RATES.SSA_CS.IBRD.EUR_USD.10Y"
    IBRD_EUR_USD_2Y = "RATES.SSA_CS.IBRD.EUR_USD.2Y"
    IBRD_EUR_USD_3Y = "RATES.SSA_CS.IBRD.EUR_USD.3Y"
    IBRD_EUR_USD_5Y = "RATES.SSA_CS.IBRD.EUR_USD.5Y"
    IBRD_EUR_USD_7Y = "RATES.SSA_CS.IBRD.EUR_USD.7Y"
    IFC_EUR_USD_10Y = "RATES.SSA_CS.IFC.EUR_USD.10Y"
    IFC_EUR_USD_2Y = "RATES.SSA_CS.IFC.EUR_USD.2Y"
    IFC_EUR_USD_3Y = "RATES.SSA_CS.IFC.EUR_USD.3Y"
    IFC_EUR_USD_5Y = "RATES.SSA_CS.IFC.EUR_USD.5Y"
    IFC_EUR_USD_7Y = "RATES.SSA_CS.IFC.EUR_USD.7Y"
    JBIC_EUR_USD_10Y = "RATES.SSA_CS.JBIC.EUR_USD.10Y"
    JBIC_EUR_USD_2Y = "RATES.SSA_CS.JBIC.EUR_USD.2Y"
    JBIC_EUR_USD_3Y = "RATES.SSA_CS.JBIC.EUR_USD.3Y"
    JBIC_EUR_USD_5Y = "RATES.SSA_CS.JBIC.EUR_USD.5Y"
    JBIC_EUR_USD_7Y = "RATES.SSA_CS.JBIC.EUR_USD.7Y"
    KBN_EUR_USD_10Y = "RATES.SSA_CS.KBN.EUR_USD.10Y"
    KBN_EUR_USD_2Y = "RATES.SSA_CS.KBN.EUR_USD.2Y"
    KBN_EUR_USD_3Y = "RATES.SSA_CS.KBN.EUR_USD.3Y"
    KBN_EUR_USD_5Y = "RATES.SSA_CS.KBN.EUR_USD.5Y"
    KBN_EUR_USD_7Y = "RATES.SSA_CS.KBN.EUR_USD.7Y"
    KFW_EUR_USD_10Y = "RATES.SSA_CS.KFW.EUR_USD.10Y"
    KFW_EUR_USD_2Y = "RATES.SSA_CS.KFW.EUR_USD.2Y"
    KFW_EUR_USD_3Y = "RATES.SSA_CS.KFW.EUR_USD.3Y"
    KFW_EUR_USD_5Y = "RATES.SSA_CS.KFW.EUR_USD.5Y"
    KFW_EUR_USD_7Y = "RATES.SSA_CS.KFW.EUR_USD.7Y"
    NEDWBK_EUR_USD_10Y = "RATES.SSA_CS.NEDWBK.EUR_USD.10Y"
    NEDWBK_EUR_USD_2Y = "RATES.SSA_CS.NEDWBK.EUR_USD.2Y"
    NEDWBK_EUR_USD_3Y = "RATES.SSA_CS.NEDWBK.EUR_USD.3Y"
    NEDWBK_EUR_USD_5Y = "RATES.SSA_CS.NEDWBK.EUR_USD.5Y"
    NEDWBK_EUR_USD_7Y = "RATES.SSA_CS.NEDWBK.EUR_USD.7Y"
    NIB_EUR_USD_2Y = "RATES.SSA_CS.NIB.EUR_USD.2Y"
    NIB_EUR_USD_3Y = "RATES.SSA_CS.NIB.EUR_USD.3Y"
    NIB_EUR_USD_5Y = "RATES.SSA_CS.NIB.EUR_USD.5Y"
    NIB_EUR_USD_7Y = "RATES.SSA_CS.NIB.EUR_USD.7Y"
    N_US_AG_EUR_USD_2Y = "RATES.SSA_CS.N_US_AG.EUR_USD.2Y"
    N_US_AG_EUR_USD_3Y = "RATES.SSA_CS.N_US_AG.EUR_USD.3Y"
    N_US_AG_EUR_USD_5Y = "RATES.SSA_CS.N_US_AG.EUR_USD.5Y"
    OKB_EUR_USD_2Y = "RATES.SSA_CS.OKB.EUR_USD.2Y"
    OKB_EUR_USD_3Y = "RATES.SSA_CS.OKB.EUR_USD.3Y"
    OKB_EUR_USD_5Y = "RATES.SSA_CS.OKB.EUR_USD.5Y"
    OKB_EUR_USD_7Y = "RATES.SSA_CS.OKB.EUR_USD.7Y"
    ONT_EUR_USD_10Y = "RATES.SSA_CS.ONT.EUR_USD.10Y"
    ONT_EUR_USD_2Y = "RATES.SSA_CS.ONT.EUR_USD.2Y"
    ONT_EUR_USD_3Y = "RATES.SSA_CS.ONT.EUR_USD.3Y"
    ONT_EUR_USD_5Y = "RATES.SSA_CS.ONT.EUR_USD.5Y"
    ONT_EUR_USD_7Y = "RATES.SSA_CS.ONT.EUR_USD.7Y"
    Q_EUR_USD_10Y = "RATES.SSA_CS.Q.EUR_USD.10Y"
    Q_EUR_USD_2Y = "RATES.SSA_CS.Q.EUR_USD.2Y"
    Q_EUR_USD_3Y = "RATES.SSA_CS.Q.EUR_USD.3Y"
    Q_EUR_USD_5Y = "RATES.SSA_CS.Q.EUR_USD.5Y"
    Q_EUR_USD_7Y = "RATES.SSA_CS.Q.EUR_USD.7Y"
    RENTEN_EUR_USD_10Y = "RATES.SSA_CS.RENTEN.EUR_USD.10Y"
    RENTEN_EUR_USD_2Y = "RATES.SSA_CS.RENTEN.EUR_USD.2Y"
    RENTEN_EUR_USD_3Y = "RATES.SSA_CS.RENTEN.EUR_USD.3Y"
    RENTEN_EUR_USD_5Y = "RATES.SSA_CS.RENTEN.EUR_USD.5Y"
    RENTEN_EUR_USD_7Y = "RATES.SSA_CS.RENTEN.EUR_USD.7Y"
    SUPRA_NTNL_EUR_USD_2Y = "RATES.SSA_CS.SUPRA_NTNL.EUR_USD.2Y"
    SUPRA_NTNL_EUR_USD_3Y = "RATES.SSA_CS.SUPRA_NTNL.EUR_USD.3Y"
    SUPRA_NTNL_EUR_USD_5Y = "RATES.SSA_CS.SUPRA_NTNL.EUR_USD.5Y"

