# fmt: off
# ruff: noqa: E501
# flake8: noqa
r"""XCCY_SWAP tags, generated from the Citi Velocity catalog. DO NOT EDIT BY HAND.

Regenerate with::

    python scripts/gen_citivelo_tag_enums.py

54 tags under ``RATES.XCCY_SWAP``, arranged as one flat enum.

Edits to this file are lost on the next regeneration, and
``tests/test_citivelo_tag_enums.py`` fails the moment it disagrees with the
catalog - so there is no window in which a hand edit merely looks like it worked.
"""

from __future__ import annotations

from Query.CitiVelocity.tag_enums._base import CitiVeloTag, TagNamespace

__all__ = ["XCCY_SWAP"]

class XCCY_SWAP(CitiVeloTag):
    """54 tags under ``RATES.XCCY_SWAP``."""

    __node__ = "RATES.XCCY_SWAP"

    AUD_USD_FWD = "RATES.XCCY_SWAP.AUD.USD.FWD"
    AUD_USD_PAR = "RATES.XCCY_SWAP.AUD.USD.PAR"
    CAD_USD_FWD = "RATES.XCCY_SWAP.CAD.USD.FWD"
    CAD_USD_PAR = "RATES.XCCY_SWAP.CAD.USD.PAR"
    CHF_USD_FWD = "RATES.XCCY_SWAP.CHF.USD.FWD"
    CHF_USD_PAR = "RATES.XCCY_SWAP.CHF.USD.PAR"
    CNH_USD_FWD = "RATES.XCCY_SWAP.CNH.USD.FWD"
    CNH_USD_PAR = "RATES.XCCY_SWAP.CNH.USD.PAR"
    DKK_USD_FWD = "RATES.XCCY_SWAP.DKK.USD.FWD"
    DKK_USD_PAR = "RATES.XCCY_SWAP.DKK.USD.PAR"
    EUR_CHF_FWD = "RATES.XCCY_SWAP.EUR.CHF.FWD"
    EUR_CHF_PAR = "RATES.XCCY_SWAP.EUR.CHF.PAR"
    EUR_DKK_FWD = "RATES.XCCY_SWAP.EUR.DKK.FWD"
    EUR_DKK_PAR = "RATES.XCCY_SWAP.EUR.DKK.PAR"
    EUR_NOK_FWD = "RATES.XCCY_SWAP.EUR.NOK.FWD"
    EUR_NOK_PAR = "RATES.XCCY_SWAP.EUR.NOK.PAR"
    EUR_SEK_FWD = "RATES.XCCY_SWAP.EUR.SEK.FWD"
    EUR_SEK_PAR = "RATES.XCCY_SWAP.EUR.SEK.PAR"
    EUR_USD_FWD = "RATES.XCCY_SWAP.EUR.USD.FWD"
    EUR_USD_PAR = "RATES.XCCY_SWAP.EUR.USD.PAR"
    GBP_USD_FWD = "RATES.XCCY_SWAP.GBP.USD.FWD"
    GBP_USD_PAR = "RATES.XCCY_SWAP.GBP.USD.PAR"
    HKD_USD_FWD = "RATES.XCCY_SWAP.HKD.USD.FWD"
    HKD_USD_PAR = "RATES.XCCY_SWAP.HKD.USD.PAR"
    HKD_HIBOR3M_USD_FWD = "RATES.XCCY_SWAP.HKD_HIBOR3M.USD.FWD"
    HKD_HIBOR3M_USD_PAR = "RATES.XCCY_SWAP.HKD_HIBOR3M.USD.PAR"
    HUF_EUR_FWD = "RATES.XCCY_SWAP.HUF.EUR.FWD"
    HUF_EUR_PAR = "RATES.XCCY_SWAP.HUF.EUR.PAR"
    ILS_USD_FWD = "RATES.XCCY_SWAP.ILS.USD.FWD"
    ILS_USD_PAR = "RATES.XCCY_SWAP.ILS.USD.PAR"
    JPY_USD_FWD = "RATES.XCCY_SWAP.JPY.USD.FWD"
    JPY_USD_PAR = "RATES.XCCY_SWAP.JPY.USD.PAR"
    KRW_USD_FWD = "RATES.XCCY_SWAP.KRW.USD.FWD"
    KRW_USD_PAR = "RATES.XCCY_SWAP.KRW.USD.PAR"
    NOK_USD_FWD = "RATES.XCCY_SWAP.NOK.USD.FWD"
    NOK_USD_PAR = "RATES.XCCY_SWAP.NOK.USD.PAR"
    NOK_NIBOR3M_USD_FWD = "RATES.XCCY_SWAP.NOK_NIBOR3M.USD.FWD"
    NOK_NIBOR3M_USD_PAR = "RATES.XCCY_SWAP.NOK_NIBOR3M.USD.PAR"
    NZD_USD_FWD = "RATES.XCCY_SWAP.NZD.USD.FWD"
    NZD_USD_PAR = "RATES.XCCY_SWAP.NZD.USD.PAR"
    SEK_USD_FWD = "RATES.XCCY_SWAP.SEK.USD.FWD"
    SEK_USD_PAR = "RATES.XCCY_SWAP.SEK.USD.PAR"
    SEK_STIBOR3M_USD_FWD = "RATES.XCCY_SWAP.SEK_STIBOR3M.USD.FWD"
    SEK_STIBOR3M_USD_PAR = "RATES.XCCY_SWAP.SEK_STIBOR3M.USD.PAR"
    SGD_USD_FWD = "RATES.XCCY_SWAP.SGD.USD.FWD"
    SGD_USD_PAR = "RATES.XCCY_SWAP.SGD.USD.PAR"
    THB_USD_FWD = "RATES.XCCY_SWAP.THB.USD.FWD"
    THB_USD_PAR = "RATES.XCCY_SWAP.THB.USD.PAR"
    TRY_USD_FWD = "RATES.XCCY_SWAP.TRY.USD.FWD"
    TRY_USD_PAR = "RATES.XCCY_SWAP.TRY.USD.PAR"
    TWD_USD_FWD = "RATES.XCCY_SWAP.TWD.USD.FWD"
    TWD_USD_PAR = "RATES.XCCY_SWAP.TWD.USD.PAR"
    ZAR_USD_FWD = "RATES.XCCY_SWAP.ZAR.USD.FWD"
    ZAR_USD_PAR = "RATES.XCCY_SWAP.ZAR.USD.PAR"

