"""Register H-F7 in the ledger. MUST run before any F7 capacity or pond number exists."""
import json
import pathlib

LEDGER = (pathlib.Path(__file__).resolve().parents[1] / "docs" / "superpowers" /
          "ledgers" / "2026-08-08-citivelo-rv-loop-ledger.jsonl")

ROW = {
    "ts": "2026-08-09T10:45:00", "id": "H-F7", "kind": "hypothesis", "family": "F7",
    "text": (
        "PRE-REGISTERED, before any capacity count, any pond number and any backtest number "
        "exists. H-F7: FADE ONLY WHAT FORCED FLOW MADE CHEAP - flow-conditioned curve RV on the "
        "capacity-passing USD spot pond. "
        "|| MECHANISM, and why it is not a thirteenth repetition: every one of the twelve dead "
        "families here is a FADE, and not one of them conditioned on WHY the dislocation exists. "
        "Huggins-Schaller ch1, which the sibling program makes a precondition, says fade richness "
        "that is TRANSIENT - forced flow, demand for immediacy - and do NOT fade structural "
        "hedging demand. A dealer who absorbs a large curve package is paid a concession for "
        "warehousing the risk; that concession is a price dislocation with a REASON to revert, and "
        "the reversion is someone else's cost rather than a statistical regularity. This is the "
        "only mechanism in the record where the edge IS a cost, paid by an identifiable party, "
        "which is the shape L-0073 says an ALIVE candidate must have. "
        "|| THE STRUCTURAL ADVANTAGE, stated because it is the one thing that distinguishes F7 "
        "from H13: THE STATE IS MEASURED ON A DIFFERENT DATASET FROM THE MARK. H13 died because "
        "its state was a function of the same Citi curves that generated its P&L (L-0051: the "
        "entire graded net was the entry-day flow; L-0066: the CM spread's ac1 = -0.392 against "
        "per-leg -0.045/-0.023, so ~39% of a daily spread move is the vendor's own bootstrap "
        "noise). F7's trigger is read off the DTCC Part 43 tape and cannot inherit that noise. "
        "The DIRECTION is still taken from the curve, so the noise is not eliminated - it is "
        "handled by the persistence requirement below and by the h>=5bd horizons. "
        "|| LINEAGE AND TRIAL COUNT, answered pre-emptively because the checker will ask exactly "
        "as it did of H-V-17: NON-SV and NON-F3. F3 faded a cross-sectional residual on "
        "forward-starting packages with no flow input; F7 trades SPOT structures and its state "
        "comes from a dataset this loop has only ever used to measure COSTS (CM-1, CM-2), never "
        "as a signal. Family = mechanism lineage, not data source (the H-V-17 precedent), and "
        "L-0042(b) plus the family-free F-gates are the precedent for starting at the loop's own "
        "count. STARTS AT LOOP N = 37. "
        "|| (1) CAPACITY GATE, RUNS FIRST, per L-0071 - this loop killed twelve families on "
        "pond-vs-boat and never asked whether the instrument trades. Universe = USD spot-starting "
        "OIS packages of 2 or 3 legs on standard tenors {1,2,3,4,5,7,10,12,15,20,25,30}, "
        "reconstructed from the LOCAL 643-day Part 43 cache by execution-timestamp linkage within "
        "a dissemination file, restricted to action == NEWT and event == TRAD (the ECONOMIC_FLOW "
        "cell, cited at 43.2 per L-0072 - but verified against the file per L-0078, not trusted). "
        "FLOOR, pre-stated now: an EXACT leg-tenor signature qualifies only if it prints >= 60 "
        "packages per 60 trading days (~1/day) in OUR OWN tape. Exact signatures, never families - "
        "the sibling FAILURE_LOG records that family counts overstate exact-structure liquidity "
        "~10x, so the sibling's own headline numbers are not admissible as our capacity evidence. "
        "DEAD AT CAPACITY, 0 trials, if fewer than 2 signatures clear the floor. "
        "|| (2) SIGNAL, built only from what was DISSEMINATED by the close of day t. Aggregation "
        "is by FILE DATE and by nothing else (L-0077: 8-30% of any file is prints executed "
        "earlier, and the un-disseminated ones are disproportionately the large blocked prints "
        "that ARE the signal). Shock S_t(structure) = that file-date's package COUNT in that exact "
        "signature, standardised against a TRAILING 60-file-day window, walk-forward only, no "
        "full-sample scalar anywhere. COUNT-based is pre-stated because 3.33% of USD notional "
        "strings are capped ('1,100,000,000+') and the cap truncates precisely the top of the size "
        "distribution; a notional-weighted arm is a REGISTERED SENSITIVITY, not a selection, and "
        "reads capped values at their floor (which understates a shock - the conservative "
        "direction). SHOCK = S_t in the top decile of its own trailing window. "
        "|| (3) DISLOCATION - magnitude and direction from the Citi EOD USD SOFR quoted par grid, "
        "never a fitted curve (design doc marking policy). Spread = r_long - r_short; fly = "
        "2*r_belly - r_wing1 - r_wing2, in bp. Signal = trailing 60bd z of that quantity, "
        "walk-forward. ENTRY REQUIRES |z| >= 1.0 AND THE SAME SIGN ON TWO CONSECUTIVE CLOSES - the "
        "persistence requirement exists specifically to step outside L-0066's one-day-reversing "
        "bootstrap noise, and it is registered here rather than tuned later. "
        "|| (4) THE REGISTERED CLAIM IS THE INCREMENT, NOT THE LEVEL. Book A (conditional) fades "
        "only on a SHOCK day; Book B (control, unconditional) fades the identical dislocation with "
        "the identical engine, sample, costs and horizons and no flow condition. The claim under "
        "test is A minus B. Fading a curve z-score IS the RiskVal gross screen and it has died "
        "twelve times, so a conditional book that merely reproduces the unconditional one is "
        "FALSIFIED however positive it looks. "
        "|| (5) GATE FORM - an ORACLE-INCREMENT gate, which consumes 0 trials on the session-1 "
        "precedent (gates that measure an upper bound consume nothing), and is deliberately NOT "
        "the V-V-17 form that measured a registered rule's realised gross and correctly consumed "
        "15. Perfect-direction reversion of the dislocation at h in {1,5,21}bd, conditional-on-"
        "shock vs unconditional, per signature. GATE PASSES ONLY IF the conditional oracle median "
        "exceeds BOTH (i) the round trip at the governing cost line AND (ii) the unconditional "
        "oracle median, on >= 2 capacity-passing signatures at the SAME h. "
        "|| (6) COST LINE, PRE-STATED BEFORE THE GATE RUNS, because this family lives exactly "
        "where the house line and CM-2 disagree by 3-4x and choosing after seeing the reversion "
        "numbers is the maker-flattering move. GOVERNING: CM-2's measured at-stamp deviation, "
        "which is FLAT in tenor at 0.315-0.528 bp from 1Y to 30Y (L-0060); per-leg half-spread "
        "taken at 0.45bp, structure RT = sum|w| x 2 x 0.45 -> 1.80bp for a 2-leg spread (sum|w|=2) "
        "and 3.60bp for a 1-2-1 fly (sum|w|=4). PRE-STATED SENSITIVITY, reported alongside and "
        "never substituted after the fact: RVUtils/cost_model's linear line (0.30 -> 1.75bp in "
        "tenor), which makes the same 10s30s RT ~4.9bp; plus the house x{0.5,1,2} band. L-0068's "
        "caveat travels with every quote: sum|w| is the DIAGONAL approximation and overstates a "
        "single balanced package by 20-40%, so the governing RT carries a stated band (1.1-1.4bp "
        "spread / 2.2-2.9bp fly) and the GATE IS JUDGED AT THE UNHAIRCUT NUMBER, the conservative "
        "end. CM-2's level is an admitted UPPER BOUND whose composition is unseparated (L-0060, "
        "L-0078) - stated, not argued around. "
        "|| (7) MARKING: Citi EOD quoted par rates, LAG-1 FILLS (signal at close t, execute at "
        "close t+1). Any graded number comes from QueryDrivenBacktest or a panel validated against "
        "a QDB replay at corr >= 0.97. Legs sized DV01-neutral; cost charged per leg on traded "
        "DV01. The QDB notebook ships the equity curve and the tearsheet/closed-position analytics "
        "per L-0076, and carries the two assertions that caught session 2's silent no-ops "
        "(non-zero marks AND a closed-position count). "
        "|| (8) PLACEBO BATTERY, pre-registered, with the fill-lag profile as its spine: "
        "(a) FILL-LAG MONOTONICITY at t+1/t+2/t+3/t+5 - a real immediacy premium decays "
        "MONOTONICALLY in fill lag, so a NON-MONOTONIC profile is a noise signature and is a KILL, "
        "not a caveat (L-0069, imported from the sibling's phase_c probes); (b) wrong-day shock, "
        "scale-matched to the same number of fire days, 200 draws; (c) shuffled-structure shock "
        "(signature X's shock applied to signature Y); (d) Book B, the unconditional control. "
        "|| (9) TRIAL COUNTING: the gate consumes 0. If graded, one trial per (signature x "
        "horizon) examined. Horizons {5,21}bd are registered AS A PAIR and both are reported; "
        "h=1 is GATE-ONLY and is never graded, because L-0066 puts 1d inside the bootstrap noise "
        "floor. Cost multipliers and the notional-weighted arm are sensitivity, not selection. "
        "|| (10) sd(SR) SOURCE, named here because per L-0064 a registration that does not name "
        "its sd source is not registered. PRIMARY: the program's accumulated cross-family "
        "per-trade Sharpe dispersion, sd(SR) = 0.275843 measured over the 14 H13 arms (range "
        "-0.784227..+0.218662, recomputed by the checker at L-0064) - a WIDER reference "
        "distribution that is emphatically NOT the F7 registered set, which is the whole point of "
        "the amendment. REPORTED SENSITIVITY, both of them, on any verdict: the narrowed source "
        "excluding the two GBP arms (sd = 0.103300) and F7's own registered set's sd. Before any "
        "config-independence claim, the L-0069 rank test runs: each signature's position vector is "
        "written in a common leg basis {1,2,3,4,5,7,10,12,15,20,25,30}Y and the RANK is reported - "
        "the number of independent configs is the rank, not the count. "
        "|| (11) SAMPLE, and an honest statement of its limit made before the numbers: the "
        "binding constraint is the Part 43 cache, 2023-12-01..2026-07-21, 643 file-days; the Citi "
        "curve covers 2005-2026 and is not binding. After the 60-day trailing window the usable "
        "sample is ~580 days, so a top-decile shock gives on the order of 58 fire days per "
        "signature before the |z| and persistence filters, and materially fewer NON-OVERLAPPING "
        "episodes at h=21. IT IS ENTIRELY POSSIBLE THAT THE INCREMENT IS REAL AND THE SAMPLE "
        "CANNOT REACH THE BAR. That outcome will be recorded as 'increment measured, bar "
        "unreachable at this sample' - it is NOT an ALIVE, it does NOT become one by pooling "
        "overlapping episodes or by dropping the deflation, and the >= 10 non-overlapping trade "
        "floor stands. "
        "|| FALSIFIED IF: (a) fewer than 2 signatures clear the capacity floor; (b) the "
        "conditional oracle median fails either prong of (5); (c) if graded - the increment A-B "
        "is <= 0 at 1x, or the median config is negative, or DSR <= 0.5 at loop N under the "
        "PRIMARY sd source, or the fill-lag profile is non-monotonic, or the wrong-day placebo "
        "opens the gate at a comparable rate, or fewer than 10 non-overlapping episodes exist."
    ),
    "trials_delta": 0, "trials_total": 37,
}


def main() -> None:
    existing = {json.loads(ln)["id"] for ln in
                LEDGER.read_text(encoding="utf-8").splitlines() if ln.strip()}
    if ROW["id"] in existing:
        print(f"SKIP {ROW['id']} (already present)")
        return
    with LEDGER.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(ROW) + "\n")
    print(f"APPEND {ROW['id']}  ({len(ROW['text'])} chars)")


if __name__ == "__main__":
    main()
