Set-Location 'C:\Users\chris\clee\ARBS-r0\r0_leadlag'
& 'C:\Users\chris\anaconda3\envs\stir\python.exe' scratch_d1_fullwin.py 1y 2>&1 | Out-File -Append -Encoding utf8 'C:\Users\chris\clee\ARBS-r0\r0_leadlag\out\_pull_b.log'
& 'C:\Users\chris\anaconda3\envs\stir\python.exe' scratch_d1_fullwin.py 3m 2>&1 | Out-File -Append -Encoding utf8 'C:\Users\chris\clee\ARBS-r0\r0_leadlag\out\_pull_b.log'
& 'C:\Users\chris\anaconda3\envs\stir\python.exe' scratch_d1_fullwin.py 1m 2>&1 | Out-File -Append -Encoding utf8 'C:\Users\chris\clee\ARBS-r0\r0_leadlag\out\_pull_b.log'
'GROUP_b_DONE' | Out-File -Append -Encoding utf8 'C:\Users\chris\clee\ARBS-r0\r0_leadlag\out\_pull_b.log'
