import datetime
from abc import ABC
from typing import Any, Optional

from Query.Base._GenericPricable import _GenericPricable
from Query.Base._GenericPricer import _GenericPricer
from Query.USTFutures._USTFutureGenericPricable import _USTFutureGenericPricable


class _USTFutureGenericPricer(_GenericPricer[_GenericPricable], ABC):
    def id(self) -> str: ...
    def reference_date(self) -> datetime.date: ...
    def meta(self) -> Any: ...

    def effective_date(self, ustf: _USTFutureGenericPricable) -> datetime.date: ...
    def maturity_date(self, ustf: _USTFutureGenericPricable) -> datetime.date: ...
    def price(self, ustf: _USTFutureGenericPricable) -> float: ...
    def yield_to_maturity(self, ustf: _USTFutureGenericPricable) -> float: ...
    def pv01(self, ustf: _USTFutureGenericPricable) -> float: ...
    def dv01(self, ustf: _USTFutureGenericPricable) -> float: ...

    def resolve_pricable(self, ustf: _USTFutureGenericPricable, risk_weight: Optional[float] = None) -> _USTFutureGenericPricable: ...

    def build_ustf(
        self,
        contract_code: Optional[str] = None,
        effective_date: Optional[datetime.date] = None,
        maturity_date: Optional[datetime.date] = None,
        price: Optional[float] = None,
        contracts: Optional[int] = None,
        notional: Optional[float] = None,
        **kwargs: Any,
    ) -> Any: ...
